// packages/auth-ui/src/svelte/ChangePasswordCard.svelte
<script lang="ts">
    import { createChangePasswordController } from "../core/change-password";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import FormField from "./FormField.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    const t = useAuthUI().localization;
    const { actions, state: form } = controllerStore(createChangePasswordController);
</script>

<AuthCard headingLevel={2} title={t.changePassword}>
    <form
        class="lunora-auth-form"
        novalidate
        onsubmit={(event) => {
            event.preventDefault();
            void actions.submit();
        }}
    >
        <FormBanner error={$form.formError} success={$form.successMessage} />
        <FormField {actions} autoComplete="current-password" field="currentPassword" fields={$form.fields} label={t.currentPasswordLabel} type="password" />
        <FormField {actions} autoComplete="new-password" field="newPassword" fields={$form.fields} label={t.newPasswordLabel} type="password" />
        <FormField {actions} autoComplete="new-password" field="confirmPassword" fields={$form.fields} label={t.confirmPasswordLabel} type="password" />
        <SubmitButton pending={$form.status === "submitting"}>{t.changePassword}</SubmitButton>
    </form>
</AuthCard>

// registry/auth-ui-vue/vue/ChangePasswordCard.vue
<script setup lang="ts">
import { createChangePasswordController } from "../core/change-password";
import AuthCard from "./AuthCard.vue";
import FormField from "./FormField.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

const { localization: t } = useAuthUI();
const { actions, state } = useController(createChangePasswordController);
</script>

<template>
    <AuthCard :headingLevel="2" :title="t.changePassword">
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.submit">
            <FormBanner :error="state.formError" :success="state.successMessage" />
            <FormField
                :actions="actions"
                field="currentPassword"
                :fields="state.fields"
                :label="t.currentPasswordLabel"
                type="password"
                autoComplete="current-password"
            />
            <FormField :actions="actions" field="newPassword" :fields="state.fields" :label="t.newPasswordLabel" type="password" autoComplete="new-password" />
            <FormField
                :actions="actions"
                field="confirmPassword"
                :fields="state.fields"
                :label="t.confirmPasswordLabel"
                type="password"
                autoComplete="new-password"
            />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.changePassword }}</SubmitButton>
        </form>
    </AuthCard>
</template>
