// registry/auth-ui-svelte/svelte/EmailOtpCard.svelte
<script lang="ts">
    import { createEmailOtpController, isFlowEnabled } from "../core";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import Field from "./Field.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    const context = useAuthUI();
    const t = context.localization;
    const enabled = isFlowEnabled(context, "emailOtp", "EmailOtpCard");
    const { actions, state: flow } = controllerStore(createEmailOtpController);
</script>

{#if enabled}
    {#if $flow.step === "verify"}
        <AuthCard description={t.emailOtpSent} title={t.emailOtp}>
            <form
                class="lunora-auth-form"
                novalidate
                onsubmit={(event) => {
                    event.preventDefault();
                    void actions.verify();
                }}
            >
                <FormBanner error={$flow.formError} />
                <Field autoComplete="one-time-code" field={$flow.code} label={t.codeLabel} name="code" onBlur={() => {}} onChange={actions.setCode} />
                <SubmitButton pending={$flow.status === "submitting"}>{t.twoFactor}</SubmitButton>
            </form>
            {#snippet footer()}
                <button class="lunora-auth-link" onclick={actions.back} type="button">{t.sendNewCode}</button>
            {/snippet}
        </AuthCard>
    {:else}
        <AuthCard title={t.emailOtp}>
            <form
                class="lunora-auth-form"
                novalidate
                onsubmit={(event) => {
                    event.preventDefault();
                    void actions.sendCode();
                }}
            >
                <FormBanner error={$flow.formError} success={$flow.successMessage} />
                <Field autoComplete="email" field={$flow.email} label={t.emailLabel} name="email" onBlur={() => {}} onChange={actions.setEmail} type="email" />
                <SubmitButton pending={$flow.status === "submitting"}>{t.emailOtp}</SubmitButton>
            </form>
        </AuthCard>
    {/if}
{/if}

// registry/auth-ui-vue/vue/EmailOtpCard.vue
<script setup lang="ts">
import { createEmailOtpController, isFlowEnabled } from "../core";
import AuthCard from "./AuthCard.vue";
import Field from "./Field.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

const context = useAuthUI();
const t = context.localization;
const enabled = isFlowEnabled(context, "emailOtp", "EmailOtpCard");
const { actions, state } = useController(createEmailOtpController);
</script>

<template>
    <AuthCard v-if="enabled && state.step === 'verify'" :title="t.emailOtp" :description="t.emailOtpSent">
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.verify">
            <FormBanner :error="state.formError" />
            <Field :field="state.code" :label="t.codeLabel" name="code" autoComplete="one-time-code" @change="actions.setCode" />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.twoFactor }}</SubmitButton>
        </form>
        <template #footer>
            <button class="lunora-auth-link" type="button" @click="actions.back">{{ t.sendNewCode }}</button>
        </template>
    </AuthCard>
    <AuthCard v-else-if="enabled" :title="t.emailOtp">
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.sendCode">
            <FormBanner :error="state.formError" :success="state.successMessage" />
            <Field :field="state.email" :label="t.emailLabel" name="email" type="email" autoComplete="email" @change="actions.setEmail" />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.emailOtp }}</SubmitButton>
        </form>
    </AuthCard>
</template>
