// registry/auth-ui-svelte/svelte/LinkedAccountsCard.svelte
<!--
    Which OAuth providers are attached, with link/unlink.

    The "available to link" list is `context.social` minus what is already
    attached — so with server discovery on, it is exactly the providers the
    deployment configured, and an app that adds one gets a new button with no
    client change.
-->
<script lang="ts">
    import { createAccountsController, linkableProviders, NON_SOCIAL_PROVIDERS } from "../core/accounts";
    import { providerLabel, rowActionLabel } from "../core/labels";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import FormBanner from "./FormBanner.svelte";
    import Skeleton from "./Skeleton.svelte";

    const context = useAuthUI();
    const t = context.localization;
    const { actions, state: res } = controllerStore(createAccountsController);

    const linkable = $derived(linkableProviders($res.items, context.social));
</script>

<AuthCard title={t.accountsTitle}>
    <FormBanner error={$res.error} />
    {#if $res.loading}
        <Skeleton />
    {:else}
        <ul class="lunora-auth-list">
            {#each $res.items as account (account.id ?? account.providerId)}
                <li class="lunora-auth-list__item">
                    <span class="lunora-auth-list__label">{providerLabel(account.providerId ?? "")}</span>
                    <!--
                        `credential` is the password and `passkey` rows belong to
                        <PasskeysCard>; offering "unlink" for either would be a
                        button that either fails or deletes the wrong thing.
                    -->
                    {#if !NON_SOCIAL_PROVIDERS.has(account.providerId ?? "")}
                        <button
                            aria-label={rowActionLabel(t.remove, providerLabel(account.providerId ?? ""))}
                            class="lunora-auth-button lunora-auth-button--danger"
                            disabled={$res.busy || $res.items.length <= 1}
                            onclick={() => {
                                void actions.unlink(account.providerId ?? "", account.accountId);
                            }}
                            type="button"
                        >
                            {t.remove}
                        </button>
                    {/if}
                </li>
            {/each}
            {#if $res.items.length === 0}
                <li class="lunora-auth-list__empty">{t.accountsEmpty}</li>
            {/if}
        </ul>
    {/if}
    {#if linkable.length > 0}
        <div class="lunora-auth-social">
            {#each linkable as provider (provider)}
                <button
                    class="lunora-auth-button lunora-auth-button--secondary"
                    disabled={$res.busy}
                    onclick={() => {
                        void actions.link(provider);
                    }}
                    type="button"
                >
                    {t.accountsLink}: {providerLabel(provider)}
                </button>
            {/each}
        </div>
    {/if}
</AuthCard>

// registry/auth-ui-vue/vue/LinkedAccountsCard.vue
<script setup lang="ts">
// Which OAuth providers are attached, with link/unlink.
//
// The "available to link" list is `context.social` minus what is already
// attached — so with server discovery on, it is exactly the providers the
// deployment configured, and an app that adds one gets a new button with no
// client change.
import { computed } from "vue";

import type { AuthAccount } from "../core/types";
import { createAccountsController, NON_SOCIAL_PROVIDERS } from "../core/accounts";
import { providerLabel } from "../core/labels";
import AuthCard from "./AuthCard.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import Skeleton from "./Skeleton.vue";
import { useController } from "./use-controller";

const context = useAuthUI();
const t = context.localization;
const { actions, state } = useController(createAccountsController);

const linkable = computed(() => {
    const linked = new Set(state.value.items.map((account) => account.providerId).filter((id): id is string => id !== undefined));

    return context.social.filter((provider) => !linked.has(provider));
});

const onUnlink = (account: AuthAccount): void => {
    void actions.unlink(account.providerId ?? "", account.accountId);
};

const onLink = (provider: string): void => {
    void actions.link(provider);
};
</script>

<template>
    <AuthCard :title="t.accountsTitle">
        <FormBanner :error="state.error" />
        <Skeleton v-if="state.loading" />
        <ul v-else class="lunora-auth-list">
            <li v-for="account in state.items" :key="account.id ?? account.providerId" class="lunora-auth-list__item">
                <span class="lunora-auth-list__label">{{ providerLabel(account.providerId ?? "") }}</span>
                <!--
                    `credential` is the password and `passkey` rows belong to
                    <PasskeysCard>; offering "unlink" for either would be a
                    button that either fails or deletes the wrong thing.
                -->
                <button
                    v-if="!NON_SOCIAL_PROVIDERS.has(account.providerId ?? '')"
                    class="lunora-auth-button lunora-auth-button--danger"
                    type="button"
                    :disabled="state.busy || state.items.length <= 1"
                    @click="onUnlink(account)"
                >
                    {{ t.remove }}
                </button>
            </li>
            <li v-if="state.items.length === 0" class="lunora-auth-list__empty">{{ t.accountsEmpty }}</li>
        </ul>
        <div v-if="linkable.length > 0" class="lunora-auth-social">
            <button
                v-for="provider in linkable"
                :key="provider"
                class="lunora-auth-button lunora-auth-button--secondary"
                type="button"
                :disabled="state.busy"
                @click="onLink(provider)"
            >
                {{ `${t.accountsLink}: ${providerLabel(provider)}` }}
            </button>
        </div>
    </AuthCard>
</template>
