// packages/auth-ui/src/svelte/ProfileCard.svelte
<script lang="ts">
    import { createProfileController } from "../core";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import Field from "./Field.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    let {
        defaultImage,
        defaultName,
    }: {
        defaultImage?: string;
        defaultName?: string;
    } = $props();

    const t = useAuthUI().localization;
    const { actions, state: form } = controllerStore((context) => createProfileController(context, { initialImage: defaultImage, initialName: defaultName }));
</script>

<AuthCard title={t.profile}>
    <form
        class="lunora-auth-form"
        novalidate
        onsubmit={(event) => {
            event.preventDefault();
            void actions.submit();
        }}
    >
        <FormBanner error={$form.formError} success={$form.successMessage} />
        <Field
            autoComplete="name"
            field={$form.fields.name}
            label={t.nameLabel}
            name="name"
            onBlur={() => {
                actions.blur("name");
            }}
            onChange={(value) => {
                actions.setField("name", value);
            }}
        />
        <SubmitButton pending={$form.status === "submitting"}>{t.saveChanges}</SubmitButton>
    </form>
</AuthCard>

// registry/auth-ui-vue/vue/ProfileCard.vue
<script setup lang="ts">
import { createProfileController } from "../core/profile";
import AuthCard from "./AuthCard.vue";
import Field from "./Field.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

const props = defineProps<{
    defaultImage?: string;
    defaultName?: string;
}>();

const { localization: t } = useAuthUI();
const { actions, state } = useController((context) => createProfileController(context, { initialImage: props.defaultImage, initialName: props.defaultName }));
</script>

<template>
    <AuthCard :title="t.profile">
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.submit">
            <FormBanner :error="state.formError" :success="state.successMessage" />
            <Field
                :field="state.fields.name"
                :label="t.nameLabel"
                name="name"
                autoComplete="name"
                @blur="actions.blur('name')"
                @change="actions.setField('name', $event)"
            />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.saveChanges }}</SubmitButton>
        </form>
    </AuthCard>
</template>
