// registry/auth-ui-svelte/svelte/ResendVerificationCard.svelte
<!-- "Send me another link" — the companion to <VerifyEmailCard>. -->
<script lang="ts">
    import { createResendVerificationController } from "../core/verify-email";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import FormField from "./FormField.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    const t = useAuthUI().localization;
    const { actions, state: form } = controllerStore(createResendVerificationController);
</script>

<AuthCard title={t.verifyEmail}>
    <form
        class="lunora-auth-form"
        novalidate
        onsubmit={(event) => {
            event.preventDefault();
            void actions.submit();
        }}
    >
        <FormBanner error={$form.formError} success={$form.successMessage} />
        <FormField {actions} autoComplete="email" field="email" fields={$form.fields} label={t.emailLabel} type="email" />
        <SubmitButton pending={$form.status === "submitting"}>{t.verifyEmailResend}</SubmitButton>
    </form>
</AuthCard>

// registry/auth-ui-vue/vue/ResendVerificationCard.vue
<script setup lang="ts">
// "Send me another link" — the companion to <VerifyEmailCard>.
import { createResendVerificationController } from "../core/verify-email";
import AuthCard from "./AuthCard.vue";
import FormField from "./FormField.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

const { localization: t } = useAuthUI();
const { actions, state } = useController(createResendVerificationController);
</script>

<template>
    <AuthCard :title="t.verifyEmail">
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.submit">
            <FormBanner :error="state.formError" :success="state.successMessage" />
            <FormField :actions="actions" field="email" :fields="state.fields" :label="t.emailLabel" type="email" autoComplete="email" />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.verifyEmailResend }}</SubmitButton>
        </form>
    </AuthCard>
</template>
