// packages/auth-ui/src/svelte/SignOutButton.svelte
<script lang="ts">
    import type { Snippet } from "svelte";

    import { signOut } from "../core/session-actions";
    import { useAuthUI } from "./context";

    let { children }: { children?: Snippet } = $props();

    const context = useAuthUI();
    // `null` rather than "" so an unthemed button renders no style attribute.
    const themeStyle =
        Object.keys(context.themeVariables).length === 0
            ? null
            : Object.entries(context.themeVariables)
                  .map(([property, value]) => `${property}:${value}`)
                  .join(";");
</script>

<button
    class="lunora-auth-button lunora-auth-button--secondary"
    onclick={() => {
        void signOut(context);
    }}
    style={themeStyle}
    type="button"
>
    {#if children}{@render children()}{:else}{context.localization.signOut}{/if}
</button>

// registry/auth-ui-vue/vue/SignOutButton.vue
<script setup lang="ts">
import { signOut } from "../core/session-actions";
import { useAuthUI } from "./provider";

const props = defineProps<{
    label?: string;
}>();

const context = useAuthUI();
const themeStyle = Object.keys(context.themeVariables).length === 0 ? undefined : context.themeVariables;

const onSignOut = (): void => {
    void signOut(context);
};
</script>

<template>
    <button class="lunora-auth-button lunora-auth-button--secondary" type="button" :style="themeStyle" @click="onSignOut">
        {{ props.label ?? context.localization.signOut }}
    </button>
</template>
