// registry/auth-ui-svelte/svelte/SignUpCard.svelte
<script lang="ts">
    import { createSignUpController } from "../core/sign-up";
    import { signInWithSocial } from "../core/social";
    import AuthCard from "./AuthCard.svelte";
    import AuthDivider from "./AuthDivider.svelte";
    import AuthLink from "./AuthLink.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import Field from "./Field.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SocialButtons from "./SocialButtons.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    let { signInHref = "/sign-in" }: { signInHref?: string } = $props();

    const context = useAuthUI();
    const t = context.localization;
    const social = context.social;
    const { actions, state: form } = controllerStore(createSignUpController);
</script>

<AuthCard title={t.signUp}>
    <!--
        Social buttons belong on sign-up too — OAuth is a sign-up path, not just a
        sign-in one, and omitting them here sends new users through a password form
        they never needed. This was the gap against better-auth-ui's <AuthView>.
    -->
    <SocialButtons
        onSelect={(provider) => {
            void signInWithSocial(context, provider);
        }}
        providers={social}
    />
    {#if social.length > 0}
        <AuthDivider />
    {/if}
    <form
        class="lunora-auth-form"
        novalidate
        onsubmit={(event) => {
            event.preventDefault();
            void actions.submit();
        }}
    >
        <FormBanner error={$form.formError} />
        <Field
            autoComplete="name"
            field={$form.fields.name}
            label={t.nameLabel}
            name="name"
            onBlur={() => {
                actions.blur("name");
            }}
            onChange={(value) => {
                actions.setField("name", value);
            }}
        />
        <Field
            autoComplete="email"
            field={$form.fields.email}
            label={t.emailLabel}
            name="email"
            onBlur={() => {
                actions.blur("email");
            }}
            onChange={(value) => {
                actions.setField("email", value);
            }}
            type="email"
        />
        <Field
            autoComplete="new-password"
            field={$form.fields.password}
            label={t.passwordLabel}
            name="password"
            onBlur={() => {
                actions.blur("password");
            }}
            onChange={(value) => {
                actions.setField("password", value);
            }}
            type="password"
        />
        <SubmitButton pending={$form.status === "submitting"}>{t.signUp}</SubmitButton>
    </form>
    {#snippet footer()}
        <AuthLink href={signInHref}>{t.haveAccount}</AuthLink>
    {/snippet}
</AuthCard>

// registry/auth-ui-vue/vue/SignUpCard.vue
<script setup lang="ts">
import { createSignUpController } from "../core/sign-up";
import { signInWithSocial } from "../core/social";
import AuthCard from "./AuthCard.vue";
import AuthDivider from "./AuthDivider.vue";
import AuthLink from "./AuthLink.vue";
import Field from "./Field.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SocialButtons from "./SocialButtons.vue";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

withDefaults(
    defineProps<{
        signInHref?: string;
    }>(),
    {
        signInHref: "/sign-in",
    },
);

const context = useAuthUI();
const t = context.localization;
const { actions, state } = useController(createSignUpController);

const onSocial = (provider: string): void => {
    void signInWithSocial(context, provider);
};
</script>

<template>
    <AuthCard :title="t.signUp">
        <!--
            Social buttons belong on sign-up too — OAuth is a sign-up path, not
            just a sign-in one, and omitting them here sends new users through a
            password form they never needed. This was the gap against
            better-auth-ui's <AuthView>.
        -->
        <SocialButtons :providers="context.social" @select="onSocial" />
        <AuthDivider v-if="context.social.length > 0" />
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.submit">
            <FormBanner :error="state.formError" />
            <Field
                :field="state.fields.name"
                :label="t.nameLabel"
                name="name"
                autoComplete="name"
                @blur="actions.blur('name')"
                @change="actions.setField('name', $event)"
            />
            <Field
                :field="state.fields.email"
                :label="t.emailLabel"
                name="email"
                type="email"
                autoComplete="email"
                @blur="actions.blur('email')"
                @change="actions.setField('email', $event)"
            />
            <Field
                :field="state.fields.password"
                :label="t.passwordLabel"
                name="password"
                type="password"
                autoComplete="new-password"
                @blur="actions.blur('password')"
                @change="actions.setField('password', $event)"
            />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.signUp }}</SubmitButton>
        </form>
        <template #footer>
            <AuthLink :href="signInHref">{{ t.haveAccount }}</AuthLink>
        </template>
    </AuthCard>
</template>
