// registry/auth-ui-svelte/svelte/TeamsCard.svelte
<!--
    Teams in the active organization.

    Gated on `context.organization.teams` rather than a flow flag: teams are an
    option of the one `organization` plugin, so no plugin id reveals them and the
    server reports them from the resolved table map instead.
-->
<script lang="ts">
    import { rowActionLabel } from "../core/labels";
    import { createTeamsController } from "../core/teams";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import Field from "./Field.svelte";
    import FormBanner from "./FormBanner.svelte";
    import Skeleton from "./Skeleton.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    const context = useAuthUI();
    const t = context.localization;
    const enabled = context.plugins.organization && context.organization.teams;
    const { actions, state: res } = controllerStore((context_) => createTeamsController(context_, { autoLoad: enabled }));

    let name = $state("");
</script>

{#if enabled}
    <AuthCard title={t.teams}>
        <FormBanner error={$res.error} />
        {#if $res.loading}
            <Skeleton rows={2} />
        {:else}
            <ul class="lunora-auth-list">
                {#each $res.items as team (team.id)}
                    <li class="lunora-auth-list__item">
                        <span class="lunora-auth-list__label">{team.name}</span>
                        <button
                            aria-label={rowActionLabel(t.remove, team.name)}
                            class="lunora-auth-button lunora-auth-button--danger"
                            disabled={$res.busy}
                            onclick={() => {
                                void actions.remove(team.id ?? "");
                            }}
                            type="button"
                        >
                            {t.remove}
                        </button>
                    </li>
                {/each}
                {#if $res.items.length === 0}
                    <li class="lunora-auth-list__empty">{t.teamsEmpty}</li>
                {/if}
            </ul>
        {/if}
        <form
            class="lunora-auth-form"
            novalidate
            onsubmit={(event) => {
                event.preventDefault();

                if (name.trim() !== "") {
                    void actions.create(name).then(() => {
                        name = "";
                    });
                }
            }}
        >
            <Field
                field={{ touched: false, value: name }}
                label={t.teamNameLabel}
                name="team"
                onBlur={() => {}}
                onChange={(value) => {
                    name = value;
                }}
            />
            <SubmitButton pending={$res.busy}>{t.saveChanges}</SubmitButton>
        </form>
    </AuthCard>
{/if}

// registry/auth-ui-vue/vue/TeamsCard.vue
<script setup lang="ts">
// Teams in the active organization.
//
// Gated on `context.organization.teams` rather than a flow flag: teams are an
// option of the one `organization` plugin, so no plugin id reveals them and the
// server reports them from the resolved table map instead.
import { ref } from "vue";

import { createTeamsController } from "../core/teams";
import AuthCard from "./AuthCard.vue";
import Field from "./Field.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import Skeleton from "./Skeleton.vue";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

const context = useAuthUI();
const t = context.localization;
// Resolved before the controller is built: a gated-off card must not fire the
// resource auto-load on mount just to render nothing.
const enabled = context.plugins.organization && context.organization.teams;
const { actions, state } = useController((context_) => createTeamsController(context_, { autoLoad: enabled }));

const name = ref("");

const onCreate = async (): Promise<void> => {
    if (name.value.trim() === "") {
        return;
    }

    await actions.create(name.value);
    name.value = "";
};

// Takes the optional id straight from the row: the template can't narrow,
// so the guard lives here rather than as a cast at the call site.
const onRemove = (id?: string): void => {
    void actions.remove(id ?? "");
};
</script>

<template>
    <AuthCard v-if="enabled" :title="t.teams">
        <FormBanner :error="state.error" />
        <Skeleton v-if="state.loading" :rows="2" />
        <ul v-else class="lunora-auth-list">
            <li v-for="team in state.items" :key="team.id" class="lunora-auth-list__item">
                <span class="lunora-auth-list__label">{{ team.name }}</span>
                <button class="lunora-auth-button lunora-auth-button--danger" type="button" :disabled="state.busy" @click="onRemove(team.id)">
                    {{ t.remove }}
                </button>
            </li>
            <li v-if="state.items.length === 0" class="lunora-auth-list__empty">{{ t.teamsEmpty }}</li>
        </ul>
        <form class="lunora-auth-form" novalidate @submit.prevent="onCreate">
            <Field :field="{ touched: false, value: name }" :label="t.teamNameLabel" name="team" @change="name = $event" />
            <SubmitButton :pending="state.busy">{{ t.saveChanges }}</SubmitButton>
        </form>
    </AuthCard>
</template>
