// packages/auth-ui/src/react/two-factor-setup-card.tsx
"use client";

import type { ReactElement } from "react";

import { isFlowEnabled } from "../core/flow-gate";
import { createTwoFactorSetupController } from "../core/two-factor-setup";
import { AuthCard, Field, FormBanner, SubmitButton } from "./primitives";
import { useAuthUI } from "./provider";
import { useController } from "./use-controller";

const onSubmit =
    (action: () => unknown) =>
    (event: { preventDefault: () => void }): void => {
        event.preventDefault();
        void action();
    };

const TwoFactorSetupCard = (): ReactElement | null => {
    const context = useAuthUI();
    const { localization: t } = context;
    const [state, actions] = useController(createTwoFactorSetupController);
    const pending = state.status === "submitting";

    if (!isFlowEnabled(context, "twoFactor", "TwoFactorSetupCard")) {
        return null;
    }

    if (state.step === "enabled") {
        return (
            <AuthCard title={t.twoFactorSetup}>
                <FormBanner error={state.error} success={t.twoFactorEnabled} />
                <form className="lunora-auth-form" noValidate onSubmit={onSubmit(actions.disable)}>
                    <Field
                        autoComplete="current-password"
                        field={state.password}
                        label={t.passwordLabel}
                        name="password"
                        onBlur={() => undefined}
                        onChange={actions.setPassword}
                        type="password"
                    />
                    <SubmitButton pending={pending}>{t.twoFactorDisable}</SubmitButton>
                </form>
            </AuthCard>
        );
    }

    if (state.step === "verify") {
        return (
            <AuthCard description={t.twoFactorScan} title={t.twoFactorSetup}>
                <FormBanner error={state.error} />
                {state.totpUri === undefined ? null : <code className="lunora-auth-code">{state.totpUri}</code>}
                {state.backupCodes.length === 0 ? null : (
                    <>
                        <p className="lunora-auth-card__description">{t.backupCodes}</p>
                        <ul className="lunora-auth-codes">
                            {state.backupCodes.map((backupCode) => (
                                <li className="lunora-auth-codes__item" key={backupCode}>
                                    {backupCode}
                                </li>
                            ))}
                        </ul>
                    </>
                )}
                <form className="lunora-auth-form" noValidate onSubmit={onSubmit(actions.verify)}>
                    <Field
                        autoComplete="one-time-code"
                        field={state.code}
                        label={t.codeLabel}
                        name="code"
                        onBlur={() => undefined}
                        onChange={actions.setCode}
                    />
                    <SubmitButton pending={pending}>{t.twoFactor}</SubmitButton>
                </form>
            </AuthCard>
        );
    }

    return (
        <AuthCard title={t.twoFactorSetup}>
            <FormBanner error={state.error} />
            <form className="lunora-auth-form" noValidate onSubmit={onSubmit(actions.enable)}>
                <Field
                    autoComplete="current-password"
                    field={state.password}
                    label={t.passwordLabel}
                    name="password"
                    onBlur={() => undefined}
                    onChange={actions.setPassword}
                    type="password"
                />
                <SubmitButton pending={pending}>{t.twoFactorEnable}</SubmitButton>
            </form>
        </AuthCard>
    );
};

export { TwoFactorSetupCard };

// registry/auth-ui-vue/vue/TwoFactorSetupCard.vue
<script setup lang="ts">
import { isFlowEnabled } from "../core/flow-gate";
import { createTwoFactorSetupController } from "../core/two-factor-setup";
import AuthCard from "./AuthCard.vue";
import Field from "./Field.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

const context = useAuthUI();
const t = context.localization;
const enabled = isFlowEnabled(context, "twoFactor", "TwoFactorSetupCard");
const { actions, state } = useController(createTwoFactorSetupController);
</script>

<template>
    <AuthCard v-if="enabled && state.step === 'enabled'" :title="t.twoFactorSetup">
        <FormBanner :error="state.error" :success="t.twoFactorEnabled" />
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.disable">
            <Field
                :field="state.password"
                :label="t.passwordLabel"
                name="password"
                type="password"
                autoComplete="current-password"
                @change="actions.setPassword"
            />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.twoFactorDisable }}</SubmitButton>
        </form>
    </AuthCard>
    <AuthCard v-else-if="enabled && state.step === 'verify'" :title="t.twoFactorSetup" :description="t.twoFactorScan">
        <FormBanner :error="state.error" />
        <code v-if="state.totpUri !== undefined" class="lunora-auth-code">{{ state.totpUri }}</code>
        <template v-if="state.backupCodes.length > 0">
            <p class="lunora-auth-card__description">{{ t.backupCodes }}</p>
            <ul class="lunora-auth-codes">
                <li v-for="backupCode in state.backupCodes" :key="backupCode" class="lunora-auth-codes__item">{{ backupCode }}</li>
            </ul>
        </template>
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.verify">
            <Field :field="state.code" :label="t.codeLabel" name="code" autoComplete="one-time-code" @change="actions.setCode" />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.twoFactor }}</SubmitButton>
        </form>
    </AuthCard>
    <AuthCard v-else-if="enabled" :title="t.twoFactorSetup">
        <FormBanner :error="state.error" />
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.enable">
            <Field
                :field="state.password"
                :label="t.passwordLabel"
                name="password"
                type="password"
                autoComplete="current-password"
                @change="actions.setPassword"
            />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.twoFactorEnable }}</SubmitButton>
        </form>
    </AuthCard>
</template>
