// registry/auth-ui-vue/vue/AuthView.vue
<script setup lang="ts">
// One route for every auth screen: mount this at `/auth/:view` and pass the
// segment, instead of wiring ten routes to ten cards.
//
// The segments are configurable through the provider's `viewPaths`, so the URLs
// stay the app's decision — this only maps whichever segment arrives to the card
// that owns it. An unrecognized segment falls back to sign-in rather than
// rendering nothing, because a typo'd auth URL should still let someone in.
import type { Component } from "vue";
import { computed } from "vue";

import AcceptInvitationCard from "./AcceptInvitationCard.vue";
import DeviceAuthorizationCard from "./DeviceAuthorizationCard.vue";
import EmailOtpCard from "./EmailOtpCard.vue";
import ForgotPasswordCard from "./ForgotPasswordCard.vue";
import MagicLinkCard from "./MagicLinkCard.vue";
import { useAuthUI } from "./provider";
import ResetPasswordCard from "./ResetPasswordCard.vue";
import SignInCard from "./SignInCard.vue";
import SignUpCard from "./SignUpCard.vue";
import TwoFactorCard from "./TwoFactorCard.vue";
import VerifyEmailCard from "./VerifyEmailCard.vue";

const props = defineProps<{
    /** The URL segment, e.g. `"sign-up"`. Falls back to the sign-in card. */
    view?: string;
}>();

const context = useAuthUI();

/*
 * Plugin-gated views are checked here rather than left to the card's own gate. A
 * card that renders nothing leaves a blank page, which on a *route* is a dead
 * end; falling back to sign-in keeps the user moving. The cards keep their own
 * gate for when they are mounted directly.
 */
const card = computed<Component>(() => {
    const { plugins, viewPaths } = context;

    switch (props.view) {
        case viewPaths.acceptInvitation: {
            return AcceptInvitationCard;
        }

        case viewPaths.deviceAuthorization: {
            return plugins.deviceAuthorization ? DeviceAuthorizationCard : SignInCard;
        }

        case viewPaths.emailOtp: {
            return plugins.emailOtp ? EmailOtpCard : SignInCard;
        }

        case viewPaths.forgotPassword: {
            return ForgotPasswordCard;
        }

        case viewPaths.magicLink: {
            return plugins.magicLink ? MagicLinkCard : SignInCard;
        }

        case viewPaths.resetPassword: {
            return ResetPasswordCard;
        }

        case viewPaths.signUp: {
            return SignUpCard;
        }

        case viewPaths.twoFactor: {
            return plugins.twoFactor ? TwoFactorCard : SignInCard;
        }

        case viewPaths.verifyEmail: {
            return VerifyEmailCard;
        }

        default: {
            return SignInCard;
        }
    }
});
</script>

<template>
    <component :is="card" />
</template>

// packages/auth-ui/src/svelte/AuthView.svelte
<!--
    One route for every auth screen: mount this at `/auth/:view` and pass the
    segment, instead of wiring ten routes to ten cards.

    The segments are configurable through the provider's `viewPaths`, so the URLs
    stay the app's decision — this only maps whichever segment arrives to the card
    that owns it. An unrecognized segment falls back to sign-in rather than
    rendering nothing, because a typo'd auth URL should still let someone in.
-->
<script lang="ts">
    import AcceptInvitationCard from "./AcceptInvitationCard.svelte";
    import { useAuthUI } from "./context";
    import DeviceAuthorizationCard from "./DeviceAuthorizationCard.svelte";
    import EmailOtpCard from "./EmailOtpCard.svelte";
    import ForgotPasswordCard from "./ForgotPasswordCard.svelte";
    import MagicLinkCard from "./MagicLinkCard.svelte";
    import ResetPasswordCard from "./ResetPasswordCard.svelte";
    import SignInCard from "./SignInCard.svelte";
    import SignUpCard from "./SignUpCard.svelte";
    import TwoFactorCard from "./TwoFactorCard.svelte";
    import VerifyEmailCard from "./VerifyEmailCard.svelte";

    let {
        view,
    }: {
        /** The URL segment, e.g. `"sign-up"`. Falls back to the sign-in card. */
        view?: string;
    } = $props();

    const { plugins, viewPaths } = useAuthUI();
</script>

<!--
    Plugin-gated views are checked here rather than left to the card's own gate. A
    card that renders nothing leaves a blank page, which on a *route* is a dead
    end; falling through to the sign-in card keeps the user moving. The cards keep
    their own gate for when they are mounted directly.
-->
{#if view === viewPaths.acceptInvitation}
    <AcceptInvitationCard />
{:else if view === viewPaths.deviceAuthorization && plugins.deviceAuthorization}
    <DeviceAuthorizationCard />
{:else if view === viewPaths.emailOtp && plugins.emailOtp}
    <EmailOtpCard />
{:else if view === viewPaths.forgotPassword}
    <ForgotPasswordCard />
{:else if view === viewPaths.magicLink && plugins.magicLink}
    <MagicLinkCard />
{:else if view === viewPaths.resetPassword}
    <ResetPasswordCard />
{:else if view === viewPaths.signUp}
    <SignUpCard />
{:else if view === viewPaths.twoFactor && plugins.twoFactor}
    <TwoFactorCard />
{:else if view === viewPaths.verifyEmail}
    <VerifyEmailCard />
{:else}
    <SignInCard />
{/if}
