// registry/auth-ui-vue/vue/AuthCard.vue
<script setup lang="ts">
// Card shell: heading, optional description, body (default slot), optional
// footer (named `footer` slot).
defineProps<{
    description?: string;
    title: string;
}>();
</script>

<template>
    <section class="lunora-auth-card">
        <header class="lunora-auth-card__header">
            <h1 class="lunora-auth-card__title">{{ title }}</h1>
            <p v-if="description !== undefined" class="lunora-auth-card__description">{{ description }}</p>
        </header>
        <div class="lunora-auth-card__body">
            <slot />
        </div>
        <footer v-if="$slots.footer" class="lunora-auth-card__footer">
            <slot name="footer" />
        </footer>
    </section>
</template>

// packages/auth-ui/src/svelte/AuthCard.svelte
<!-- Card shell: heading, optional description, body, and optional footer. -->
<script lang="ts">
    import type { Snippet } from "svelte";

    let {
        children,
        description,
        footer,
        title,
    }: {
        children: Snippet;
        description?: string;
        footer?: Snippet;
        title: string;
    } = $props();
</script>

<section class="lunora-auth-card">
    <header class="lunora-auth-card__header">
        <h1 class="lunora-auth-card__title">{title}</h1>
        {#if description !== undefined}
            <p class="lunora-auth-card__description">{description}</p>
        {/if}
    </header>
    <div class="lunora-auth-card__body">{@render children()}</div>
    {#if footer !== undefined}
        <footer class="lunora-auth-card__footer">{@render footer()}</footer>
    {/if}
</section>
