// registry/auth-ui-vue/vue/BackupCodesCard.vue
<script setup lang="ts">
// Regenerate two-factor backup codes.
//
// The new codes are shown once and never again — they are not refetchable by
// design — so they render inline on success rather than behind a navigation the
// user might not come back from.
import { onScopeDispose, shallowRef } from "vue";

import { createBackupCodesController } from "../core/backup-codes";
import { isFlowEnabled } from "../core/flow-gate";
import AuthCard from "./AuthCard.vue";
import Field from "./Field.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

const context = useAuthUI();
const t = context.localization;
const enabled = isFlowEnabled(context, "twoFactor", "BackupCodesCard");
/*
 * The codes live on a second store beside the form (see `core/backup-codes.ts`),
 * so this card binds both: the form through `useController`, the codes through
 * their own subscription. `handle.controller.destroy` releases both.
 */
const handle = createBackupCodesController(context);
const { actions, state } = useController(() => handle.controller);

const codes = shallowRef<ReadonlyArray<string>>(handle.getCodes());
const stop = handle.subscribeCodes(() => {
    codes.value = handle.getCodes();
});

onScopeDispose(stop);
</script>

<template>
    <AuthCard v-if="enabled" :title="t.backupCodesRegenerate">
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.submit">
            <FormBanner :error="state.formError" :success="state.successMessage" />
            <Field
                :field="state.fields.password"
                :label="t.currentPasswordLabel"
                name="password"
                type="password"
                autoComplete="current-password"
                @blur="actions.blur('password')"
                @change="actions.setField('password', $event)"
            />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.backupCodesRegenerate }}</SubmitButton>
        </form>
        <template v-if="codes.length > 0">
            <p class="lunora-auth-note">{{ t.backupCodes }}</p>
            <ul class="lunora-auth-codes">
                <li v-for="code in codes" :key="code" class="lunora-auth-codes__item">{{ code }}</li>
            </ul>
        </template>
    </AuthCard>
</template>

// packages/auth-ui/src/svelte/BackupCodesCard.svelte
<!--
    Regenerate two-factor backup codes.

    The new codes are shown once and never again — they are not refetchable by
    design — so they render inline on success rather than behind a navigation the
    user might not come back from.
-->
<script lang="ts">
    import { createBackupCodesController } from "../core/backup-codes";
    import { isFlowEnabled } from "../core/flow-gate";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import Field from "./Field.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    const context = useAuthUI();
    const t = context.localization;
    const enabled = isFlowEnabled(context, "twoFactor", "BackupCodesCard");
    // The codes live beside the form controller rather than inside it (see
    // `backup-codes.ts`), so the handle is created here and its controller handed
    // to the store seam — which still owns creation and disposal.
    const handle = createBackupCodesController(context);
    const { actions, state: form } = controllerStore(() => handle.controller);

    let codes = $state<ReadonlyArray<string>>(handle.getCodes());
</script>

{#if enabled}
    <AuthCard title={t.backupCodesRegenerate}>
        <form
            class="lunora-auth-form"
            novalidate
            onsubmit={(event) => {
                event.preventDefault();
                void actions.submit().then(() => {
                    codes = handle.getCodes();
                });
            }}
        >
            <FormBanner error={$form.formError} success={$form.successMessage} />
            <Field
                autoComplete="current-password"
                field={$form.fields.password}
                label={t.currentPasswordLabel}
                name="password"
                onBlur={() => {
                    actions.blur("password");
                }}
                onChange={(value) => {
                    actions.setField("password", value);
                }}
                type="password"
            />
            <SubmitButton pending={$form.status === "submitting"}>{t.backupCodesRegenerate}</SubmitButton>
        </form>
        {#if codes.length > 0}
            <p class="lunora-auth-note">{t.backupCodes}</p>
            <ul class="lunora-auth-codes">
                {#each codes as code (code)}
                    <li class="lunora-auth-codes__item">{code}</li>
                {/each}
            </ul>
        {/if}
    </AuthCard>
{/if}
