// registry/auth-ui-vue/vue/ChangeEmailCard.vue
<script setup lang="ts">
import { createChangeEmailController } from "../core/change-email";
import AuthCard from "./AuthCard.vue";
import FormField from "./FormField.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

const { localization: t } = useAuthUI();
const { actions, state } = useController(createChangeEmailController);
</script>

<template>
    <AuthCard :headingLevel="2" :title="t.changeEmail">
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.submit">
            <FormBanner :error="state.formError" :success="state.successMessage" />
            <FormField :actions="actions" field="newEmail" :fields="state.fields" :label="t.newEmailLabel" type="email" autoComplete="email" />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.changeEmail }}</SubmitButton>
        </form>
    </AuthCard>
</template>

// packages/auth-ui/src/svelte/ChangeEmailCard.svelte
<script lang="ts">
    import { createChangeEmailController } from "../core/change-email";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import FormField from "./FormField.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    const t = useAuthUI().localization;
    const { actions, state: form } = controllerStore(createChangeEmailController);
</script>

<AuthCard headingLevel={2} title={t.changeEmail}>
    <form
        class="lunora-auth-form"
        novalidate
        onsubmit={(event) => {
            event.preventDefault();
            void actions.submit();
        }}
    >
        <FormBanner error={$form.formError} success={$form.successMessage} />
        <FormField {actions} autoComplete="email" field="newEmail" fields={$form.fields} label={t.newEmailLabel} type="email" />
        <SubmitButton pending={$form.status === "submitting"}>{t.changeEmail}</SubmitButton>
    </form>
</AuthCard>
