// registry/auth-ui-vue/vue/DeleteAccountCard.vue
<script setup lang="ts">
import { createDeleteAccountController } from "../core/delete-account";
import AuthCard from "./AuthCard.vue";
import Field from "./Field.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

const { localization: t } = useAuthUI();
const { actions, state } = useController(createDeleteAccountController);
</script>

<template>
    <AuthCard :title="t.deleteAccount" :description="t.deleteAccountWarning">
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.submit">
            <FormBanner :error="state.formError" />
            <Field
                :field="state.fields.password"
                :label="t.passwordLabel"
                name="password"
                type="password"
                autoComplete="current-password"
                @blur="actions.blur('password')"
                @change="actions.setField('password', $event)"
            />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.deleteAccount }}</SubmitButton>
        </form>
    </AuthCard>
</template>

// packages/auth-ui/src/svelte/DeleteAccountCard.svelte
<script lang="ts">
    import { createDeleteAccountController } from "../core/delete-account";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import Field from "./Field.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    const t = useAuthUI().localization;
    const { actions, state: form } = controllerStore(createDeleteAccountController);
</script>

<AuthCard description={t.deleteAccountWarning} title={t.deleteAccount}>
    <form
        class="lunora-auth-form"
        novalidate
        onsubmit={(event) => {
            event.preventDefault();
            void actions.submit();
        }}
    >
        <FormBanner error={$form.formError} />
        <Field
            autoComplete="current-password"
            field={$form.fields.password}
            label={t.passwordLabel}
            name="password"
            onBlur={() => {
                actions.blur("password");
            }}
            onChange={(value) => {
                actions.setField("password", value);
            }}
            type="password"
        />
        <SubmitButton pending={$form.status === "submitting"}>{t.deleteAccount}</SubmitButton>
    </form>
</AuthCard>
