// packages/auth-ui/src/vue/Field.vue
<script setup lang="ts">
import { computed, useId } from "vue";

import type { FieldState } from "../core";

// A labelled text input wired to a core FieldState. Emits `blur` and `change`
// (with the next value) so the card forwards them to the controller.
const props = withDefaults(
    defineProps<{
        autoComplete?: string;
        field: FieldState;
        label: string;
        name: string;
        placeholder?: string;
        type?: "email" | "password" | "text";
    }>(),
    {
        type: "text",
    },
);

const emit = defineEmits<{
    blur: [];
    change: [value: string];
}>();

const id = useId();
const errorId = `${id}-error`;
const showError = computed(() => props.field.touched && props.field.error !== undefined);
</script>

<template>
    <div class="lunora-auth-field">
        <label class="lunora-auth-field__label" :for="id">{{ label }}</label>
        <input
            :id="id"
            class="lunora-auth-field__input"
            :name="name"
            :type="type"
            :value="field.value"
            :autocomplete="autoComplete"
            :placeholder="placeholder"
            :aria-invalid="showError"
            :aria-describedby="showError ? errorId : undefined"
            @blur="emit('blur')"
            @input="emit('change', ($event.target as HTMLInputElement).value)"
        />
        <p v-if="showError" :id="errorId" class="lunora-auth-field__error">{{ field.error }}</p>
    </div>
</template>

// packages/auth-ui/src/svelte/Field.svelte
<!-- A labelled text input wired to a core FieldState. -->
<script lang="ts" module>
    // Module-scoped counter gives each field a stable, unique id for its
    // label/error association (the Svelte analogue of React's `useId`).
    let counter = 0;
    const nextFieldId = (): number => {
        counter += 1;

        return counter;
    };
</script>

<script lang="ts">
    import type { FieldState } from "../core";

    let {
        autoComplete,
        field,
        label,
        name,
        onBlur,
        onChange,
        placeholder,
        type = "text",
    }: {
        autoComplete?: AutoFill;
        field: FieldState;
        label: string;
        name: string;
        onBlur: () => void;
        onChange: (value: string) => void;
        placeholder?: string;
        type?: "email" | "password" | "text";
    } = $props();

    const id = `lunora-auth-field-${nextFieldId()}`;
    const errorId = `${id}-error`;
    const showError = $derived(field.touched && field.error !== undefined);
</script>

<div class="lunora-auth-field">
    <label class="lunora-auth-field__label" for={id}>{label}</label>
    <input
        aria-describedby={showError ? errorId : undefined}
        aria-invalid={showError}
        autocomplete={autoComplete}
        class="lunora-auth-field__input"
        {id}
        {name}
        onblur={onBlur}
        oninput={(event) => {
            onChange(event.currentTarget.value);
        }}
        {placeholder}
        {type}
        value={field.value}
    />
    {#if showError}
        <p class="lunora-auth-field__error" id={errorId}>{field.error}</p>
    {/if}
</div>
