// registry/auth-ui-vue/vue/SubmitButton.vue
<script setup lang="ts">
// Primary submit button with a pending state.
defineProps<{
    pending: boolean;
}>();
</script>

<template>
    <button class="lunora-auth-button" type="submit" :disabled="pending">
        <span v-if="pending" aria-hidden="true" class="lunora-auth-button__spinner" />
        <slot />
    </button>
</template>

// packages/auth-ui/src/svelte/SubmitButton.svelte
<!-- Primary submit button with a pending state. -->
<script lang="ts">
    import type { Snippet } from "svelte";

    let {
        children,
        pending,
    }: {
        children: Snippet;
        pending: boolean;
    } = $props();
</script>

<button class="lunora-auth-button" disabled={pending} type="submit">
    {#if pending}
        <span aria-hidden="true" class="lunora-auth-button__spinner"></span>
    {/if}
    {@render children()}
</button>
