// packages/auth-ui/src/vue/TwoFactorCard.vue
<script setup lang="ts">
import { createTwoFactorVerifyController, isFlowEnabled } from "../core";
import AuthCard from "./AuthCard.vue";
import Field from "./Field.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

const props = defineProps<{
    method?: "otp" | "totp";
    trustDevice?: boolean;
}>();

const context = useAuthUI();
const t = context.localization;
const enabled = isFlowEnabled(context, "twoFactor", "TwoFactorCard");
const { actions, state } = useController((context_) => createTwoFactorVerifyController(context_, { method: props.method, trustDevice: props.trustDevice }));
</script>

<template>
    <AuthCard v-if="enabled" :title="t.twoFactor">
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.submit">
            <FormBanner :error="state.formError" />
            <Field
                :field="state.fields.code"
                :label="t.codeLabel"
                name="code"
                autoComplete="one-time-code"
                @blur="actions.blur('code')"
                @change="actions.setField('code', $event)"
            />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.twoFactor }}</SubmitButton>
        </form>
    </AuthCard>
</template>

// packages/auth-ui/src/svelte/TwoFactorCard.svelte
<script lang="ts">
    import { createTwoFactorVerifyController, isFlowEnabled } from "../core";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import Field from "./Field.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    let {
        method,
        trustDevice,
    }: {
        method?: "otp" | "totp";
        trustDevice?: boolean;
    } = $props();

    const context = useAuthUI();
    const t = context.localization;
    const enabled = isFlowEnabled(context, "twoFactor", "TwoFactorCard");
    // `method` / `trustDevice` are read once at mount.
    const { actions, state: form } = controllerStore((context) => createTwoFactorVerifyController(context, { method, trustDevice }));
</script>

{#if enabled}
    <AuthCard title={t.twoFactor}>
        <form
            class="lunora-auth-form"
            novalidate
            onsubmit={(event) => {
                event.preventDefault();
                void actions.submit();
            }}
        >
            <FormBanner error={$form.formError} />
            <Field
                autoComplete="one-time-code"
                field={$form.fields.code}
                label={t.codeLabel}
                name="code"
                onBlur={() => {
                    actions.blur("code");
                }}
                onChange={(value) => {
                    actions.setField("code", value);
                }}
            />
            <SubmitButton pending={$form.status === "submitting"}>{t.twoFactor}</SubmitButton>
        </form>
    </AuthCard>
{/if}
