// registry/auth-ui-vue/vue/UserButton.vue
<script setup lang="ts">
// The avatar menu: who is signed in, plus sign-out and whatever the app hangs
// off it (passed as the default slot — links, an organization switcher, …).
//
// It is a disclosure rather than a `<menu>` because its contents are app-defined
// and forcing those into menu item semantics would mislabel them. That is also
// why the trigger carries no `aria-haspopup`: the attribute promises a menu, and
// with it the arrow-key navigation a disclosure does not implement. Escape and
// outside-click close it, and focus returns to the trigger, which is the part
// hand-rolled dropdowns usually miss.
import { onScopeDispose, ref, useId, useTemplateRef, watch } from "vue";

import { createSessionController, userLabel } from "../core/session";
import { signOut } from "../core/session-actions";
import { useAuthUI } from "./provider";
import { useController } from "./use-controller";
import UserAvatar from "./UserAvatar.vue";
import UserView from "./UserView.vue";

defineProps<{
    /** Render nothing at all when signed out, instead of a sign-in link. */
    hideWhenSignedOut?: boolean;
}>();

const context = useAuthUI();
const t = context.localization;
const { actions, state } = useController(createSessionController);

const open = ref(false);
const root = useTemplateRef<HTMLDivElement>("root");
const trigger = useTemplateRef<HTMLButtonElement>("trigger");
// Generated, not hard-coded: two menus on one page must not collide.
const menuId = useId();

const close = (): void => {
    open.value = false;
    trigger.value?.focus();
};

const onKeyDown = (event: KeyboardEvent): void => {
    if (event.key === "Escape") {
        close();
    }
};

const onPointerDown = (event: MouseEvent): void => {
    if (root.value && !root.value.contains(event.target as Node)) {
        // Not `close()`: a click elsewhere is the user moving on, and yanking
        // focus back to the trigger would fight them for it.
        open.value = false;
    }
};

const detach = (): void => {
    document.removeEventListener("keydown", onKeyDown);
    document.removeEventListener("mousedown", onPointerDown);
};

// Document listeners only exist while the menu is open, so a page full of these
// doesn't accumulate handlers for menus nobody has touched.
watch(open, (value) => {
    if (value) {
        document.addEventListener("keydown", onKeyDown);
        document.addEventListener("mousedown", onPointerDown);
    } else {
        detach();
    }
});

onScopeDispose(detach);

const onToggle = (): void => {
    open.value = !open.value;
};

const onSignOut = (): void => {
    open.value = false;
    void signOut(context).then(actions.refetch);
};
</script>

<template>
    <!--
        "Not asked yet" and "asked, nobody home" look identical in `user`, and
        rendering a sign-in link during the first request makes every page flash
        one. `settled` is the difference.
    -->
    <span v-if="!state.settled" class="lunora-auth-userbutton lunora-auth-userbutton--loading" />
    <a v-else-if="state.user === undefined && hideWhenSignedOut !== true" class="lunora-auth-link" :href="context.redirects.signIn">{{ t.signIn }}</a>
    <div v-else-if="state.user !== undefined" ref="root" class="lunora-auth-userbutton">
        <button
            ref="trigger"
            class="lunora-auth-userbutton__trigger"
            type="button"
            :aria-controls="open ? menuId : undefined"
            :aria-expanded="open"
            :aria-label="userLabel(state.user)"
            @click="onToggle"
        >
            <UserAvatar :user="state.user" />
        </button>
        <div v-if="open" :id="menuId" class="lunora-auth-userbutton__menu">
            <div class="lunora-auth-userbutton__header">
                <UserView :user="state.user" />
            </div>
            <slot />
            <button class="lunora-auth-button lunora-auth-button--secondary" type="button" @click="onSignOut">{{ t.signOut }}</button>
        </div>
    </div>
</template>

// packages/auth-ui/src/svelte/UserButton.svelte
<!--
    The avatar menu: who is signed in, plus sign-out and whatever the app hangs
    off it.

    It is a disclosure rather than a `<menu>` because its contents are app-defined
    — links, an organization switcher, a theme row — and forcing those into menu
    item semantics would mislabel them. That is also why the trigger carries no
    `aria-haspopup`: the attribute promises a menu, and with it the arrow-key
    navigation a disclosure does not implement. Escape and outside-click close it, and
    focus returns to the trigger, which is the part hand-rolled dropdowns usually
    miss.
-->
<script module lang="ts">
    // Per-instance ids: two menus on one page must not collide.
    let counter = 0;
</script>

<script lang="ts">
    import type { Snippet } from "svelte";

    import { createSessionController, userLabel } from "../core/session";
    import { signOut } from "../core/session-actions";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import UserAvatar from "./UserAvatar.svelte";
    import UserView from "./UserView.svelte";

    let {
        children,
        hideWhenSignedOut,
    }: {
        /** Extra rows rendered above sign-out (links, an org switcher, …). */
        children?: Snippet;
        /** Render nothing at all when signed out, instead of a sign-in link. */
        hideWhenSignedOut?: boolean;
    } = $props();

    // eslint-disable-next-line no-useless-assignment -- the increment is the point: a module-level counter handing out one DOM id per instance.
    const menuId = `lunora-auth-menu-${(counter += 1)}`;
    const context = useAuthUI();
    const t = context.localization;
    const { actions, state: session } = controllerStore(createSessionController);

    let open = $state(false);
    let root = $state<HTMLDivElement | undefined>(undefined);
    let trigger = $state<HTMLButtonElement | undefined>(undefined);

    const close = (): void => {
        open = false;
        trigger?.focus();
    };

    // Listeners only exist while the menu is open, so a page full of closed
    // disclosures costs nothing.
    $effect(() => {
        if (!open) {
            return undefined;
        }

        const onKeyDown = (event: KeyboardEvent): void => {
            if (event.key === "Escape") {
                close();
            }
        };

        const onPointerDown = (event: MouseEvent): void => {
            if (root && !root.contains(event.target as Node)) {
                // Not `close()`: a click elsewhere is the user moving on, and
                // yanking focus back to the trigger would fight them for it.
                open = false;
            }
        };

        document.addEventListener("keydown", onKeyDown);
        document.addEventListener("mousedown", onPointerDown);

        return () => {
            document.removeEventListener("keydown", onKeyDown);
            document.removeEventListener("mousedown", onPointerDown);
        };
    });
</script>

{#if !$session.settled}
    <!--
        "Not asked yet" and "asked, nobody home" look identical in `user`, and
        rendering a sign-in link during the first request makes every page flash
        one. `settled` is the difference.
    -->
    <span class="lunora-auth-userbutton lunora-auth-userbutton--loading"></span>
{:else if $session.user === undefined}
    {#if hideWhenSignedOut !== true}
        <a class="lunora-auth-link" href={context.redirects.signIn}>{t.signIn}</a>
    {/if}
{:else}
    <div bind:this={root} class="lunora-auth-userbutton">
        <button
            aria-controls={open ? menuId : undefined}
            aria-expanded={open}
            aria-label={userLabel($session.user)}
            bind:this={trigger}
            class="lunora-auth-userbutton__trigger"
            onclick={() => {
                open = !open;
            }}
            type="button"
        >
            <UserAvatar user={$session.user} />
        </button>
        {#if open}
            <div class="lunora-auth-userbutton__menu" id={menuId}>
                <div class="lunora-auth-userbutton__header">
                    <UserView user={$session.user} />
                </div>
                {#if children}{@render children()}{/if}
                <button
                    class="lunora-auth-button lunora-auth-button--secondary"
                    onclick={() => {
                        open = false;
                        void signOut(context).then(actions.refetch);
                    }}
                    type="button"
                >
                    {t.signOut}
                </button>
            </div>
        {/if}
    </div>
{/if}
