// packages/solid/src/hydrate-preloaded.ts
import type { FunctionReference, Preloaded, SubscriptionErrorCallback } from "@lunora/client";
import type { Accessor } from "solid-js";
import { createSignal } from "solid-js";

import { useLunora } from "./context";
import { onMounted } from "./solid-compat";

/**
 * Hydrate a query from a {@link Preloaded} token produced by `preloadQuery`
 * during SSR, then keep it live.
 *
 * This is the client half of PLAN4's "your loaders are live" handoff. The
 * returned accessor is seeded **synchronously** from `preloaded.value`, so the
 * very first read — during hydration — returns the server-rendered value with
 * no loading flash and no `Suspense` fallback (unlike `createResource`, which
 * always starts pending). Once the component mounts, a WebSocket subscription
 * attaches and every subsequent server delta flows into the same signal, so the
 * UI goes live with zero refetch.
 *
 * ```tsx
 * // route loader (server): const preloaded = await preloadQuery(client, api.messages.list, args);
 * const messages = hydratePreloaded(preloaded); // seeded from SSR, then live
 * return <pre>{JSON.stringify(messages())}</pre>;
 * ```
 *
 * Mount callbacks do not run on the server during SSR (both Solid majors defer
 * them until after hydration), so the subscription is strictly client-side —
 * the seed is the only value the server render ever sees.
 *
 * Pass `onError` to surface a subscription-scoped error the server pushes (a
 * session expiry, an RLS denial). Without it such an error is dropped and the
 * accessor keeps rendering the SSR snapshot as if it were live.
 *
 * The preloaded value was read for whoever was signed in when the page loaded.
 * After a sign-out or user switch retires that identity
 * (`client.identityEpoch() > 0`), every `hydratePreloaded` on the client (mounted
 * then or later) stops using it and returns `undefined` until the live value
 * arrives — matching `@lunora/react`'s `usePreloadedQuery`.
 */
const hydratePreloaded = <T>(preloaded: Preloaded<T>, options: { onError?: SubscriptionErrorCallback } = {}): Accessor<T> => {
    const client = useLunora();

    const { args, functionPath, shardKey, value } = preloaded;

    // Seed synchronously: the signal already holds the SSR value before the
    // first render reads it, so there is no `undefined`/loading window.
    const [data, setData] = createSignal<T>(client.identityEpoch() === 0 ? value : (undefined as T));

    const functionRef: FunctionReference = { __lunoraRef: functionPath };

    onMounted(() => {
        const offIdentity = client.onIdentityChange(() => setData(() => undefined as T));
        const unsubscribe = client.subscribe(functionRef, args, (next) => setData(() => next as T), { onError: options.onError, shardKey });

        return () => {
            offIdentity();
            unsubscribe();
        };
    });

    return data;
};

export default hydratePreloaded;

// packages/angular/src/hydrate-preloaded.ts
import type { Signal } from "@angular/core";
import { DestroyRef, inject, signal } from "@angular/core";
import type { FunctionReference, LunoraClient, Preloaded, SubscriptionError } from "@lunora/client";

import { resolveLunoraClient } from "./client";
import { shouldOpenSubscription } from "./platform";

/**
 * `HydratePreloadedOptions` is part of the experimental `@lunora/angular` API and may change without a major version bump.
 * @experimental
 */
export interface HydratePreloadedOptions {
    /** Client to bind to. Defaults to the injected `LUNORA_CLIENT`. */
    client?: LunoraClient;

    /** `DestroyRef` whose `onDestroy` tears the subscription down. Defaults to `inject(DestroyRef)`. */
    destroyRef?: DestroyRef;
}

/**
 * `HydratePreloadedResult` is part of the experimental `@lunora/angular` API and may change without a major version bump.
 * @experimental
 */
export interface HydratePreloadedResult<T> {
    /** The latest value pushed by the server. Seeded synchronously from the preloaded value until an identity is retired. */
    data: Signal<T | undefined>;

    /** The latest subscription error, or `undefined`. */
    error: Signal<SubscriptionError | undefined>;
}

/**
 * Hydrate a query from a {@link Preloaded} token produced by `preloadQuery`
 * during SSR, then keep it live — the Angular half of the reactive-loader
 * handoff.
 *
 * The returned signal is seeded **synchronously** from `preloaded.value`, so the
 * very first read (during hydration) shows the server value: no loading flash,
 * no hydration mismatch. After seeding it opens a WebSocket subscription on the
 * same `(functionPath, args, shardKey)` the SSR loader used, so every later
 * server delta updates the signal exactly like `liveQuery`.
 *
 * The subscription tears down when the owning `DestroyRef` fires.
 *
 * The preloaded value was read for whoever was signed in when the page loaded.
 * After a sign-out or user switch retires that identity
 * (`client.identityEpoch() > 0`), every `hydratePreloaded` on the client (created
 * then or later) stops using it and `data` holds `undefined` until the live value
 * arrives — matching `@lunora/react`'s `usePreloadedQuery`.
 *
 * Call from an injection context:
 * ```ts
 * readonly { data, error } = hydratePreloaded(preloadedMessages);
 * ```
 * @experimental
 */
export const hydratePreloaded = <T>(preloaded: Preloaded<T>, options: HydratePreloadedOptions = {}): HydratePreloadedResult<T> => {
    const client = resolveLunoraClient(options.client);
    const fromInjectionContext = options.destroyRef === undefined;
    const destroyRef = options.destroyRef ?? inject(DestroyRef);

    const { args, functionPath, shardKey, value } = preloaded;

    const data = signal<T | undefined>(client.identityEpoch() === 0 ? value : undefined);
    const error = signal<SubscriptionError | undefined>(undefined);

    const functionReference: FunctionReference = { __lunoraRef: functionPath };

    // During SSR the signal keeps its synchronous seed (`preloaded.value`) — the
    // server value renders with no loading flash — but no socket is opened. The
    // browser render re-runs this, re-seeds, and attaches the live subscription.
    if (shouldOpenSubscription(fromInjectionContext)) {
        const unsubscribe = client.subscribe(
            functionReference,
            args,
            (next) => {
                data.set(next as T);
                error.set(undefined);
            },
            {
                onError: (error_) => {
                    error.set(error_);
                },
                shardKey,
            },
        );

        const offIdentity = client.onIdentityChange(() => {
            data.set(undefined);
        });

        destroyRef.onDestroy(() => {
            offIdentity();
            unsubscribe();
        });
    }

    return { data: data.asReadonly(), error: error.asReadonly() };
};
