// packages/auth-ui/src/solid/provider.tsx
import { LunoraError } from "@lunora/errors";
import type { Component, Context, JSX } from "solid-js";
import { createContext, createMemo, useContext } from "solid-js";

import type { AuthUIConfig, ControllerContext } from "../core/config";
import { resolveContext } from "../core/config";
import { defaultNav } from "../core/default-nav";

/** A framework `Link` component for internal navigation (Solid Router `A`, plain `<a>`, …). */
type AuthUILink = Component<{ children: JSX.Element; class?: string; href: string }>;

/** The Solid context also carries an optional framework `Link` for internal navigation. */
interface AuthUISolidContext {
    core: ControllerContext;
    Link?: AuthUILink;
}

const AuthUIContext: Context<AuthUISolidContext | undefined> = createContext<AuthUISolidContext | undefined>();

interface AuthUIProviderProps extends Omit<AuthUIConfig, "nav"> {
    children: JSX.Element;

    /**
     * Framework `Link` component for internal links (Solid Router `A`, …). Falls
     * back to a plain `<a>` when omitted.
     */
    Link?: AuthUILink;
    /** Router bridge; defaults to a `location`-based fallback. */
    nav?: AuthUIConfig["nav"];
}

/**
 * Provides the resolved auth-UI context to the tree. One base Solid component set
 * serves every setup: pass your router into `nav`/`Link` and the cards navigate
 * through it.
 *
 * The config is resolved in a {@link createMemo}, but treat it as read once:
 * cards capture the context when they are created, so swapping `authClient` or
 * `nav` afterwards won't reach an already-mounted card. Configure the provider
 * at mount, as you would a router.
 */
const AuthUIProvider = (props: AuthUIProviderProps): JSX.Element => {
    const value = createMemo<AuthUISolidContext>(() => {
        return {
            core: resolveContext({
                authClient: props.authClient,
                basePath: props.basePath,
                localization: props.localization,
                nav: props.nav ?? defaultNav,
                onError: props.onError,
                onSessionChange: props.onSessionChange,
                plugins: props.plugins,
                redirects: props.redirects,
                social: props.social,
                theme: props.theme,
            }),
            Link: props.Link,
        };
    });

    return <AuthUIContext.Provider value={value()}>{props.children}</AuthUIContext.Provider>;
};

/** Read the resolved core controller context from the nearest provider. */
const useAuthUI = (): ControllerContext => {
    const value = useContext(AuthUIContext);

    if (!value) {
        throw new LunoraError("INTERNAL", "useAuthUI must be used inside <AuthUIProvider />");
    }

    return value.core;
};

/** Read the optional framework `Link` from the nearest provider. */
const useAuthUILink = (): AuthUILink | undefined => useContext(AuthUIContext)?.Link;

export type { AuthUILink, AuthUIProviderProps };
export { AuthUIProvider, useAuthUI, useAuthUILink };

// apps/cloud/lunora/auth-ui/react/provider.tsx
"use client";

import { LunoraError } from "@lunora/errors";
import type { ComponentType, ReactElement, ReactNode } from "react";
import { createContext, use, useEffect, useMemo, useRef, useState } from "react";

import type { AuthUIConfig, ControllerContext } from "../core";
import { resolveContext } from "../core/config";
import { defaultNav } from "../core/default-nav";
import { resolveThemeVariables } from "../core/theme";

/** The React context also carries an optional framework `Link` for internal navigation. */
interface AuthUIReactContext {
    core: ControllerContext;
    Link?: ComponentType<{ children: ReactNode; className?: string; href: string }>;
}

const AuthUIContext = createContext<AuthUIReactContext | null>(null);

interface AuthUIProviderProps extends Omit<AuthUIConfig, "nav"> {
    children: ReactNode;

    /**
     * Framework `Link` component for internal links (Next `Link`, react-router
     * `Link`, …). Falls back to a plain `&lt;a>` when omitted.
     */
    Link?: ComponentType<{ children: ReactNode; className?: string; href: string }>;
    /** Router bridge; defaults to a `location`-based fallback. */
    nav?: AuthUIConfig["nav"];
}

/**
 * Provides the resolved auth-UI context to the tree. One base React component
 * set serves every meta-framework: pass your router into `nav`/`Link` (Next,
 * react-router, TanStack Start, Astro islands) and the cards navigate through it.
 */
const AuthUIProvider = ({
    authClient,
    basePath,
    children,
    Link,
    localization,
    nav,
    onError,
    onSessionChange,
    plugins,
    redirects,
    social,
    theme,
}: AuthUIProviderProps): ReactElement => {
    /*
     * Callbacks and `nav` are naturally written inline (`nav={{ navigate: (to) =>
     * navigate(to) }}`), so a new identity arrives on every parent render. If those
     * identities reached the memo below, the context — and with it every controller
     * memoized on it — would be rebuilt mid-typing: fields blank, resource cards
     * refetch. So they are held in refs and reached through stable wrappers, and
     * only *values* participate in the key.
     */
    const latest = useRef({ nav, onError, onSessionChange });

    useEffect(() => {
        latest.current = { nav, onError, onSessionChange };
    }, [nav, onError, onSessionChange]);

    /*
     * A lazy `useState` initializer, not `useRef(...).current`: both keep the
     * first object forever, but reading `.current` during render is a ref read
     * the React Compiler refuses to optimize around (`react-hooks-js/refs`).
     * `useState`'s initial value is a plain render-safe value. Nothing ever
     * calls the setter, so this is a constant; every field reads through
     * `latest` at call time.
     */
    const [handlers] = useState(() => {
        return {
            nav: {
                navigate: (to: string): void => {
                    (latest.current.nav ?? defaultNav).navigate(to);
                },
                replace: (to: string): void => {
                    (latest.current.nav ?? defaultNav).replace(to);
                },
            },
            onError: (error: unknown): void => {
                latest.current.onError?.(error);
            },
            onSessionChange: (): void => {
                latest.current.onSessionChange?.();
            },
        };
    });

    // `theme` is a function, so its identity is as unstable as the callbacks —
    // key on what it *returns* instead, which is what the cards actually consume.
    const themeKey = JSON.stringify(resolveThemeVariables(theme));
    const configKey = JSON.stringify({ basePath, localization, plugins, redirects, social });

    const core = useMemo<ControllerContext>(
        () =>
            resolveContext({
                authClient,
                basePath,
                localization,
                nav: handlers.nav,
                onError: handlers.onError,
                onSessionChange: handlers.onSessionChange,
                plugins,
                redirects,
                social,
                theme,
            }),
        // eslint-disable-next-line react-hooks/exhaustive-deps -- object props are folded into configKey/themeKey; callbacks are ref-backed and stable.
        [authClient, handlers, configKey, themeKey],
    );

    // `Link` is deliberately outside the `core` memo: swapping it must not
    // recreate the controllers, only re-render the links.
    const value = useMemo<AuthUIReactContext>(() => {
        return { core, Link };
    }, [core, Link]);

    return <AuthUIContext value={value}>{children}</AuthUIContext>;
};

/** Read the resolved core controller context from the nearest provider. */
const useAuthUI = (): ControllerContext => {
    const value = use(AuthUIContext);

    if (!value) {
        throw new LunoraError("INTERNAL", "useAuthUI must be used inside <AuthUIProvider />");
    }

    return value.core;
};

/** Read the optional framework `Link` from the nearest provider. */
const useAuthUILink = (): AuthUIProviderProps["Link"] | undefined => use(AuthUIContext)?.Link;

export type { AuthUIProviderProps };

export { AuthUIProvider, useAuthUI, useAuthUILink };
