// templates/next/components/message-feed.tsx
"use client";

import type { Preloaded, ReturnOf } from "lunorash/client";
import { useMutation, usePreloadedQuery } from "@lunora/react";
import { useState } from "react";

import { api } from "../lunora/_generated/api";

const channelId = "channel:demo" as const;

/**
 * Client component that receives the RSC-produced `Preloaded` token.
 * `usePreloadedQuery` seeds TanStack Query's cache with the server value — the
 * first render shows it with no loading flash and no hydration mismatch — then
 * attaches a live WebSocket subscription that updates `data` on every server
 * delta.
 */
export function MessageFeed({ preloaded }: { preloaded: Preloaded<ReturnOf<typeof api.messages.list>> }) {
    const data = usePreloadedQuery(preloaded);

    const { mutate, pending } = useMutation(api.messages.send);
    const [draft, setDraft] = useState("");

    return (
        <section>
            <pre>{JSON.stringify(data, undefined, 2)}</pre>
            <form
                onSubmit={(event) => {
                    event.preventDefault();

                    if (!draft) {
                        return;
                    }

                    void mutate({ channelId, text: draft });
                    setDraft("");
                }}
            >
                <input onChange={(event) => setDraft(event.target.value)} placeholder="Say something" value={draft} />
                <button disabled={pending} type="submit">
                    Send
                </button>
            </form>
        </section>
    );
}

// templates/nuxt/components/MessageFeed.vue
<script setup lang="ts">
import type { Preloaded, ReturnOf } from "lunorash/client";
import { hydratePreloaded, useMutation } from "@lunora/vue";
import { ref } from "vue";

import { api } from "../lunora/_generated/api";

const channelId = "channel:demo" as const;

const props = defineProps<{
    preloaded: Preloaded<ReturnOf<typeof api.messages.list>>;
}>();

// `hydratePreloaded` seeds the ref SYNCHRONOUSLY from the SSR token — the first
// render shows the server value with no loading flash — then attaches a live WS
// subscription that updates `data` on every server delta.
const data = hydratePreloaded(props.preloaded);

const { mutate, pending } = useMutation(api.messages.send);
const draft = ref("");

const submit = async (): Promise<void> => {
    if (!draft.value) {
        return;
    }

    const text = draft.value;
    draft.value = "";
    await mutate({ channelId, text });
};
</script>

<template>
    <section>
        <pre>{{ JSON.stringify(data, null, 2) }}</pre>
        <form @submit.prevent="submit">
            <input v-model="draft" placeholder="Say something" />
            <button type="submit" :disabled="pending">Send</button>
        </form>
    </section>
</template>
