// registry/auth-ui-solid-v2/solid-v2/provider.tsx
import { LunoraError } from "@lunora/errors";
import type { JSX } from "@solidjs/web";
import type { Component, Context } from "solid-js";
import { createContext, createMemo, createSignal, onCleanup, Show, useContext } from "solid-js";

import type { AuthUIConfig, ControllerContext } from "../core/config";
import { DEFAULT_BASE_PATH, resolveContext } from "../core/config";
import { defaultNav } from "../core/default-nav";
import type { DiscoveredConfig } from "../core/discovery";
import { discoverAuthConfig } from "../core/discovery";

/** A framework `Link` component for internal navigation (Solid Router `A`, plain `<a>`, …). */
type AuthUILink = Component<{ children: JSX.Element; class?: string; href: string }>;

/** The Solid context also carries an optional framework `Link` for internal navigation. */
interface AuthUISolidContext {
    core: ControllerContext;
    Link?: AuthUILink;
}

const AuthUIContext: Context<AuthUISolidContext | undefined> = createContext<AuthUISolidContext | undefined>();

interface AuthUIProviderProps extends Omit<AuthUIConfig, "nav"> {
    children: JSX.Element;

    /**
     * Framework `Link` component for internal links (Solid Router `A`, …). Falls
     * back to a plain `<a>` when omitted.
     */
    Link?: AuthUILink;
    /** Router bridge; defaults to a `location`-based fallback. */
    nav?: AuthUIConfig["nav"];
}

/**
 * Provides the resolved auth-UI context to the tree. One base Solid component set
 * serves every setup: pass your router into `nav`/`Link` and the cards navigate
 * through it.
 *
 * Treat the config as read once: cards capture the context when they are
 * created, so swapping `authClient` afterwards won't reach an already-mounted
 * card. Configure the provider at mount, as you would a router.
 *
 * The one exception is server discovery, which by definition answers *after*
 * mount. Its answer produces a **new** context object, and the keyed `<Show>`
 * below re-creates the tree on that new identity. That is load-bearing rather
 * than incidental: every card resolves its gate once in its body
 * (`const enabled = isFlowEnabled(context, …)`) and passes the answer to its
 * controller's `autoLoad`, so a context mutated in place would freeze every gate
 * at its pre-discovery value — a card the server says doesn't exist would stay
 * rendered, having already fired a request that 404s. Discovery settles exactly
 * once, early, so this costs one rebuild.
 */
const AuthUIProvider = (props: AuthUIProviderProps): JSX.Element => {
    /*
     * Callbacks are naturally written inline (`nav={{ navigate: (to) =>
     * navigate(to) }}`), so they are reached through stable wrappers rather than
     * captured. Two reasons, both about *not* rebuilding: the memo below never
     * reads those props, so nothing a callback expression closes over can retrigger
     * it; and a swapped callback reaches controllers that were created earlier,
     * because the wrapper reads through at call time. Only *values* — and the
     * discovered config — decide the context identity.
     */
    const handlers = {
        nav: {
            navigate: (to: string): void => {
                (props.nav ?? defaultNav).navigate(to);
            },
            replace: (to: string): void => {
                (props.nav ?? defaultNav).replace(to);
            },
        },
        onError: (error: unknown): void => {
            props.onError?.(error);
        },
        onSessionChange: (): void => {
            props.onSessionChange?.();
        },

        /*
         * `avatar.upload` gets the same treatment, with one wrinkle: only its
         * *presence* is a config decision (it decides whether the card shows a
         * file picker or a URL field), so presence is read into the memo while
         * the function itself is reached through here.
         */
        upload: async (file: File): Promise<string> => {
            const handler = props.avatar?.upload;

            if (handler === undefined) {
                throw new LunoraError("INTERNAL", "no avatar upload handler is configured");
            }

            return handler(file);
        },
    };

    /*
     * Ask the server which plugins and providers are on. The request is shared
     * process-wide per endpoint (see `discovery.ts`), so mounting several
     * providers costs one fetch; subscribing here is what turns the answer into
     * a rebuilt context. Reading the handle synchronously — rather than in an
     * effect — means a cached answer is already in the first render.
     */
    const handle = props.discover === false ? undefined : discoverAuthConfig(props.basePath ?? DEFAULT_BASE_PATH);

    /*
     * SEEDED, not written after the fact. Solid 2 rejects a write to reactive
     * state from inside an owned scope, and a component body is one — the 1.x
     * spelling (`createSignal(undefined)` then `setDiscovered(...)` here) throws
     * `REACTIVE_WRITE_IN_OWNED_SCOPE`. Seeding keeps the same property: a cached
     * answer is already in the first render, with no effect round-trip.
     *
     * `ownedWrite` covers the subscription below: the discovery handle may
     * notify synchronously while `subscribe` is still running — i.e. still inside
     * this component's scope — and that write is this component's own state,
     * which is exactly what the option is for.
     */
    const [discovered, setDiscovered] = createSignal<DiscoveredConfig | undefined>(handle?.getState().config, { ownedWrite: true });

    if (handle !== undefined) {
        onCleanup(
            handle.subscribe(() => {
                setDiscovered(() => handle.getState().config);
            }),
        );
    }

    const core = createMemo<ControllerContext>(() =>
        resolveContext(
            {
                authClient: props.authClient,
                avatar: { maxSize: props.avatar?.maxSize, upload: props.avatar?.upload === undefined ? undefined : handlers.upload },
                basePath: props.basePath,
                forgotPassword: props.forgotPassword,
                localization: props.localization,
                nav: handlers.nav,
                onError: handlers.onError,
                onSessionChange: handlers.onSessionChange,
                organization: props.organization,
                password: props.password,
                plugins: props.plugins,
                redirects: props.redirects,
                social: props.social,
                theme: props.theme,
                viewPaths: props.viewPaths,
            },
            discovered(),
        ),
    );

    return (
        // `keyed`, so the tree is disposed and re-created on the new context
        // *identity* discovery produces. A Solid context value is read once by
        // each consumer, so an in-place field swap would reach nothing; and the
        // disposal is what re-runs each card's gate and lets `createController`
        // destroy the controller built against the stale context.
        //
        // `Link` is deliberately a getter rather than part of the keyed value:
        // swapping it must re-render the links, not re-create every controller.
        <Show keyed when={core()}>
            {(resolved) => (
                <AuthUIContext
                    value={{
                        core: resolved,
                        get Link() {
                            return props.Link;
                        },
                    }}
                >
                    {props.children}
                </AuthUIContext>
            )}
        </Show>
    );
};

/** Read the resolved core controller context from the nearest provider. */
const useAuthUI = (): ControllerContext => {
    const value = useContext(AuthUIContext);

    if (!value) {
        throw new LunoraError("INTERNAL", "useAuthUI must be used inside <AuthUIProvider />");
    }

    return value.core;
};

/** Read the optional framework `Link` from the nearest provider. */
const useAuthUILink = (): AuthUILink | undefined => useContext(AuthUIContext)?.Link;

export type { AuthUILink, AuthUIProviderProps };
export { AuthUIProvider, useAuthUI, useAuthUILink };

// registry/auth-ui-react/react/provider.tsx
"use client";

import { LunoraError } from "@lunora/errors";
import type { ComponentType, ReactElement, ReactNode } from "react";
import { createContext, use, useEffect, useMemo, useRef, useState, useSyncExternalStore } from "react";

import type { AuthUIConfig, ControllerContext, DiscoveryState } from "../core";
import { DEFAULT_BASE_PATH, resolveContext } from "../core/config";
import { defaultNav } from "../core/default-nav";
import { discoverAuthConfig } from "../core/discovery";
import { resolveThemeVariables } from "../core/theme";

/**
 * The snapshot used when discovery is off. Module-level so its identity is
 * stable — `useSyncExternalStore` re-renders forever if `getSnapshot` returns a
 * fresh object each call.
 */
const NO_DISCOVERY: DiscoveryState = { status: "unavailable" };

const noopSubscribe = (): (() => void) => () => {};

const readNoDiscovery = (): DiscoveryState => NO_DISCOVERY;

/** The React context also carries an optional framework `Link` for internal navigation. */
interface AuthUIReactContext {
    core: ControllerContext;
    Link?: ComponentType<{ children: ReactNode; className?: string; href: string }>;
}

const AuthUIContext = createContext<AuthUIReactContext | null>(null);

interface AuthUIProviderProps extends Omit<AuthUIConfig, "nav"> {
    children: ReactNode;

    /**
     * Framework `Link` component for internal links (Next `Link`, react-router
     * `Link`, …). Falls back to a plain `&lt;a>` when omitted.
     */
    Link?: ComponentType<{ children: ReactNode; className?: string; href: string }>;
    /** Router bridge; defaults to a `location`-based fallback. */
    nav?: AuthUIConfig["nav"];
}

/**
 * Provides the resolved auth-UI context to the tree. One base React component
 * set serves every meta-framework: pass your router into `nav`/`Link` (Next,
 * react-router, TanStack Start, Astro islands) and the cards navigate through it.
 */
const AuthUIProvider = ({
    authClient,
    avatar,
    basePath,
    children,
    discover,
    forgotPassword,
    Link,
    localization,
    nav,
    onError,
    onSessionChange,
    organization,
    password,
    plugins,
    redirects,
    social,
    theme,
    viewPaths,
}: AuthUIProviderProps): ReactElement => {
    /*
     * Callbacks and `nav` are naturally written inline (`nav={{ navigate: (to) =>
     * navigate(to) }}`), so a new identity arrives on every parent render. If those
     * identities reached the memo below, the context — and with it every controller
     * memoized on it — would be rebuilt mid-typing: fields blank, resource cards
     * refetch. So they are held in refs and reached through stable wrappers, and
     * only *values* participate in the key.
     */
    const latest = useRef({ avatar, nav, onError, onSessionChange });

    useEffect(() => {
        latest.current = { avatar, nav, onError, onSessionChange };
    }, [avatar, nav, onError, onSessionChange]);

    /*
     * A lazy `useState` initializer, not `useRef(...).current`: both keep the
     * first object forever, but reading `.current` during render is a ref read
     * the React Compiler refuses to optimize around (`react-hooks-js/refs`).
     * `useState`'s initial value is a plain render-safe value. Nothing ever
     * calls the setter, so this is a constant; every field reads through
     * `latest` at call time.
     */
    const [handlers] = useState(() => {
        return {
            nav: {
                navigate: (to: string): void => {
                    (latest.current.nav ?? defaultNav).navigate(to);
                },
                replace: (to: string): void => {
                    (latest.current.nav ?? defaultNav).replace(to);
                },
            },
            onError: (error: unknown): void => {
                latest.current.onError?.(error);
            },
            onSessionChange: (): void => {
                latest.current.onSessionChange?.();
            },
            /*
             * `avatar.upload` is a callback like the rest, so it gets the same
             * treatment: a stable wrapper that reads through `latest`. Without
             * this, an inline `upload={async (file) => …}` would either rebuild
             * every controller on each render or be captured stale forever.
             */
            upload: async (file: File): Promise<string> => {
                const upload = latest.current.avatar?.upload;

                if (upload === undefined) {
                    throw new LunoraError("INTERNAL", "no avatar upload handler is configured");
                }

                return upload(file);
            },
        };
    });

    /*
     * Ask the server which plugins and providers are on. The request is shared
     * process-wide per endpoint (see `discovery.ts`), so mounting several
     * providers costs one fetch; subscribing here is what turns the answer into
     * a re-render.
     */
    const handle = useMemo(() => (discover === false ? undefined : discoverAuthConfig(basePath ?? DEFAULT_BASE_PATH)), [discover, basePath]);
    const discovery = useSyncExternalStore(handle?.subscribe ?? noopSubscribe, handle?.getState ?? readNoDiscovery, readNoDiscovery);

    // `theme` is a function, so its identity is as unstable as the callbacks —
    // key on what it *returns* instead, which is what the cards actually consume.
    const themeKey = JSON.stringify(resolveThemeVariables(theme));
    const configKey = JSON.stringify({
        avatar: { hasUpload: avatar?.upload !== undefined, maxSize: avatar?.maxSize },
        basePath,
        forgotPassword,
        localization,
        organization,
        password,
        plugins,
        redirects,
        social,
        viewPaths,
    });
    // The discovered payload is a fresh object per fetch but settles exactly
    // once, so keying on its content keeps the memo from churning on re-renders
    // while still rebuilding the context when the answer lands.
    const discoveryKey = JSON.stringify(discovery.config ?? null);

    const core = useMemo<ControllerContext>(
        () =>
            resolveContext(
                {
                    authClient,
                    // Only `upload`'s *presence* is a config decision (it decides
                    // whether the card shows a file picker or a URL field); the
                    // function itself is reached through the stable wrapper.
                    avatar: { maxSize: avatar?.maxSize, upload: avatar?.upload === undefined ? undefined : handlers.upload },
                    basePath,
                    forgotPassword,
                    localization,
                    nav: handlers.nav,
                    onError: handlers.onError,
                    onSessionChange: handlers.onSessionChange,
                    organization,
                    password,
                    plugins,
                    redirects,
                    social,
                    theme,
                    viewPaths,
                },
                discovery.config,
            ),
        // eslint-disable-next-line react-hooks/exhaustive-deps -- object props are folded into configKey/themeKey/discoveryKey; callbacks are ref-backed and stable.
        [authClient, handlers, configKey, themeKey, discoveryKey],
    );

    // `Link` is deliberately outside the `core` memo: swapping it must not
    // recreate the controllers, only re-render the links.
    const value = useMemo<AuthUIReactContext>(() => {
        return { core, Link };
    }, [core, Link]);

    return <AuthUIContext value={value}>{children}</AuthUIContext>;
};

/** Read the resolved core controller context from the nearest provider. */
const useAuthUI = (): ControllerContext => {
    const value = use(AuthUIContext);

    if (!value) {
        throw new LunoraError("INTERNAL", "useAuthUI must be used inside <AuthUIProvider />");
    }

    return value.core;
};

/** Read the optional framework `Link` from the nearest provider. */
const useAuthUILink = (): AuthUIProviderProps["Link"] | undefined => use(AuthUIContext)?.Link;

export type { AuthUIProviderProps };
// eslint-disable-next-line react-refresh/only-export-components -- hooks are colocated with the provider by convention (mirrors @lunora/react's lunora-provider).
export { AuthUIProvider, useAuthUI, useAuthUILink };
