// registry/auth-ui-svelte/svelte/AcceptInvitationCard.svelte
<!--
    The screen an organization invitation link lands on.

    It renders the organization's name before asking for a decision — an "Accept"
    button with nothing above it is not consent — and bounces through sign-in when
    there is no session, returning to this same invitation afterwards.
-->
<script lang="ts">
    import { queryParameter } from "../core/browser-location";
    import { createAcceptInvitationController } from "../core/invitations";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import FormBanner from "./FormBanner.svelte";
    import Skeleton from "./Skeleton.svelte";

    let {
        invitationId,
    }: {
        /** Defaults to `?invitationId=` from the URL. */
        invitationId?: string;
    } = $props();

    const t = useAuthUI().localization;
    const { actions, state: flow } = controllerStore((context) =>
        createAcceptInvitationController(context, { invitationId: invitationId ?? queryParameter("invitationId") }),
    );
</script>

<AuthCard description={$flow.invitation?.organizationName} title={t.invitationTitle}>
    <FormBanner error={$flow.error} />
    {#if $flow.loading}
        <Skeleton rows={2} />
    {:else}
        <div class="lunora-auth-actions">
            <button
                class="lunora-auth-button"
                disabled={$flow.status === "submitting" || $flow.invitation === undefined}
                onclick={() => {
                    void actions.accept();
                }}
                type="button"
            >
                {t.invitationAccept}
            </button>
            <button
                class="lunora-auth-button lunora-auth-button--secondary"
                disabled={$flow.status === "submitting" || $flow.invitation === undefined}
                onclick={() => {
                    void actions.reject();
                }}
                type="button"
            >
                {t.invitationReject}
            </button>
        </div>
    {/if}
</AuthCard>

// packages/auth-ui/src/vue/AcceptInvitationCard.vue
<script setup lang="ts">
// The screen an organization invitation link lands on.
//
// It renders the organization's name before asking for a decision — an "Accept"
// button with nothing above it is not consent — and bounces through sign-in when
// there is no session, returning to this same invitation afterwards.
import { queryParameter } from "../core/browser-location";
import { createAcceptInvitationController } from "../core/invitations";
import AuthCard from "./AuthCard.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import Skeleton from "./Skeleton.vue";
import { useController } from "./use-controller";

const props = defineProps<{
    /** Defaults to `?invitationId=` from the URL. */
    invitationId?: string;
}>();

const { localization: t } = useAuthUI();
// Captured at setup: the controller loads this one invitation on creation, so a
// different id means a different card, not a new state.
const invitationId = props.invitationId ?? queryParameter("invitationId");
const { actions, state } = useController((context) => createAcceptInvitationController(context, { invitationId }));

const onAccept = (): void => {
    void actions.accept();
};

const onReject = (): void => {
    void actions.reject();
};
</script>

<template>
    <AuthCard :title="t.invitationTitle" :description="state.invitation?.organizationName">
        <FormBanner :error="state.error" />
        <Skeleton v-if="state.loading" :rows="2" />
        <div v-else class="lunora-auth-actions">
            <button class="lunora-auth-button" type="button" :disabled="state.status === 'submitting' || state.invitation === undefined" @click="onAccept">
                {{ t.invitationAccept }}
            </button>
            <button
                class="lunora-auth-button lunora-auth-button--secondary"
                type="button"
                :disabled="state.status === 'submitting' || state.invitation === undefined"
                @click="onReject"
            >
                {{ t.invitationReject }}
            </button>
        </div>
    </AuthCard>
</template>
