// registry/auth-ui-svelte/svelte/AdminUsersCard.svelte
<!--
    The admin plugin's user table.

    Every action here is destructive or privilege-changing, so none of them are
    optimistic and none are one click from a row's primary target — impersonation
    in particular navigates away rather than mutating in place, because the whole
    app is a different user afterwards.
-->
<script lang="ts">
    import { createAdminUsersController } from "../core/admin-users";
    import { isFlowEnabled } from "../core/flow-gate";
    import { ROLE_OPTIONS } from "../core/labels";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import FormBanner from "./FormBanner.svelte";
    import Skeleton from "./Skeleton.svelte";

    const context = useAuthUI();
    const t = context.localization;
    const enabled = isFlowEnabled(context, "admin", "AdminUsersCard");
    const { actions, state: res } = controllerStore((context_) => createAdminUsersController(context_, { autoLoad: enabled }));

    const roles = ["user", ...ROLE_OPTIONS];
</script>

{#if enabled}
    <AuthCard title={t.adminTitle}>
        <FormBanner error={$res.error} />
        <input
            aria-label={t.adminSearch}
            class="lunora-auth-field__input"
            oninput={(event) => {
                void actions.setSearch(event.currentTarget.value);
            }}
            placeholder={t.adminSearch}
            type="search"
            value={$res.extra.search}
        />
        {#if $res.loading}
            <Skeleton />
        {:else}
            <ul class="lunora-auth-list">
                {#each $res.items as user (user.id)}
                    <li class="lunora-auth-list__item">
                        <span class="lunora-auth-list__label">
                            {user.email}
                            {#if user.banned === true}
                                <span class="lunora-auth-badge">{t.adminBan}</span>
                            {/if}
                        </span>
                        <span class="lunora-auth-list__actions">
                            <select
                                aria-label={t.roleLabel}
                                class="lunora-auth-select"
                                disabled={$res.busy}
                                onchange={(event) => {
                                    void actions.setRole(user.id ?? "", event.currentTarget.value);
                                }}
                                value={user.role ?? "user"}
                            >
                                {#each roles as role (role)}
                                    <option value={role}>{role}</option>
                                {/each}
                            </select>
                            <button
                                class="lunora-auth-button lunora-auth-button--secondary"
                                disabled={$res.busy}
                                onclick={() => {
                                    void actions.impersonate(user.id ?? "");
                                }}
                                type="button"
                            >
                                {t.adminImpersonate}
                            </button>
                            <button
                                class="lunora-auth-button lunora-auth-button--danger"
                                disabled={$res.busy}
                                onclick={() => {
                                    void (user.banned === true ? actions.unban(user.id ?? "") : actions.ban(user.id ?? ""));
                                }}
                                type="button"
                            >
                                {user.banned === true ? t.adminUnban : t.adminBan}
                            </button>
                        </span>
                    </li>
                {/each}
                {#if $res.items.length === 0}
                    <li class="lunora-auth-list__empty">{t.adminUsersEmpty}</li>
                {/if}
            </ul>
        {/if}
    </AuthCard>
{/if}

// packages/auth-ui/src/vue/AdminUsersCard.vue
<script setup lang="ts">
// The admin plugin's user table.
//
// Every action here is destructive or privilege-changing, so none of them are
// optimistic and none are one click from a row's primary target — impersonation
// in particular navigates away rather than mutating in place, because the whole
// app is a different user afterwards.
import { computed } from "vue";

import type { AuthAdminUser } from "../core/types";
import { createAdminUsersController } from "../core/admin-users";
import { isFlowEnabled } from "../core/flow-gate";
import { ROLE_OPTIONS } from "../core/labels";
import AuthCard from "./AuthCard.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUIContextRef } from "./provider";
import Skeleton from "./Skeleton.vue";
import { useController } from "./use-controller";

const context = useAuthUIContextRef();
const t = context.value.localization;
// Computed, not read at setup: `setup()` never re-runs, so a gate resolved here
// would stay frozen on the pre-discovery answer. See `provider.ts`.
const enabled = computed(() => isFlowEnabled(context.value, "admin", "AdminUsersCard"));
// Read inside the factory rather than captured: `useController` re-runs it when
// the discovered context lands, and a gated-off card must not fire the resource
// auto-load just to render nothing.
const { actions, state } = useController((context_) => createAdminUsersController(context_, { autoLoad: enabled.value }));

// "user" is the role better-auth assigns when none was set, so it heads the list
// even though it is not one of the invitable roles.
const roleOptions: ReadonlyArray<string> = ["user", ...ROLE_OPTIONS];

const onSearch = (event: Event): void => {
    void actions.setSearch((event.target as HTMLInputElement).value);
};

const onRole = (user: AuthAdminUser, event: Event): void => {
    void actions.setRole(user.id ?? "", (event.target as HTMLSelectElement).value);
};

const onImpersonate = (user: AuthAdminUser): void => {
    void actions.impersonate(user.id ?? "");
};

const onBanToggle = (user: AuthAdminUser): void => {
    void (user.banned === true ? actions.unban(user.id ?? "") : actions.ban(user.id ?? ""));
};
</script>

<template>
    <AuthCard v-if="enabled" :title="t.adminTitle">
        <FormBanner :error="state.error" />
        <input
            class="lunora-auth-field__input"
            type="search"
            :aria-label="t.adminSearch"
            :placeholder="t.adminSearch"
            :value="state.extra.search"
            @input="onSearch"
        />
        <Skeleton v-if="state.loading" />
        <ul v-else class="lunora-auth-list">
            <li v-for="user in state.items" :key="user.id" class="lunora-auth-list__item">
                <span class="lunora-auth-list__label">
                    {{ user.email }}
                    <span v-if="user.banned === true" class="lunora-auth-badge">{{ t.adminBan }}</span>
                </span>
                <span class="lunora-auth-list__actions">
                    <select
                        class="lunora-auth-select"
                        :aria-label="t.roleLabel"
                        :disabled="state.busy || user.id === undefined"
                        :value="user.role ?? 'user'"
                        @change="onRole(user, $event)"
                    >
                        <option v-for="role in roleOptions" :key="role" :value="role">{{ role }}</option>
                    </select>
                    <button
                        class="lunora-auth-button lunora-auth-button--secondary"
                        type="button"
                        :disabled="state.busy || user.id === undefined"
                        @click="onImpersonate(user)"
                    >
                        {{ t.adminImpersonate }}
                    </button>
                    <button
                        class="lunora-auth-button lunora-auth-button--danger"
                        type="button"
                        :disabled="state.busy || user.id === undefined"
                        @click="onBanToggle(user)"
                    >
                        {{ user.banned === true ? t.adminUnban : t.adminBan }}
                    </button>
                </span>
            </li>
            <li v-if="state.items.length === 0" class="lunora-auth-list__empty">{{ t.adminUsersEmpty }}</li>
        </ul>
    </AuthCard>
</template>
