// registry/auth-ui-svelte/svelte/ChangePasswordCard.svelte
<script lang="ts">
    import { createChangePasswordController } from "../core/change-password";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import Field from "./Field.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    const t = useAuthUI().localization;
    const { actions, state: form } = controllerStore(createChangePasswordController);
</script>

<AuthCard headingLevel={2} title={t.changePassword}>
    <form
        class="lunora-auth-form"
        novalidate
        onsubmit={(event) => {
            event.preventDefault();
            void actions.submit();
        }}
    >
        <FormBanner error={$form.formError} success={$form.successMessage} />
        <Field
            autoComplete="current-password"
            field={$form.fields.currentPassword}
            label={t.currentPasswordLabel}
            name="currentPassword"
            onBlur={() => {
                actions.blur("currentPassword");
            }}
            onChange={(value) => {
                actions.setField("currentPassword", value);
            }}
            type="password"
        />
        <Field
            autoComplete="new-password"
            field={$form.fields.newPassword}
            label={t.newPasswordLabel}
            name="newPassword"
            onBlur={() => {
                actions.blur("newPassword");
            }}
            onChange={(value) => {
                actions.setField("newPassword", value);
            }}
            type="password"
        />
        <Field
            autoComplete="new-password"
            field={$form.fields.confirmPassword}
            label={t.confirmPasswordLabel}
            name="confirmPassword"
            onBlur={() => {
                actions.blur("confirmPassword");
            }}
            onChange={(value) => {
                actions.setField("confirmPassword", value);
            }}
            type="password"
        />
        <SubmitButton pending={$form.status === "submitting"}>{t.changePassword}</SubmitButton>
    </form>
</AuthCard>

// packages/auth-ui/src/vue/ChangePasswordCard.vue
<script setup lang="ts">
import { createChangePasswordController } from "../core/change-password";
import AuthCard from "./AuthCard.vue";
import Field from "./Field.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

const { localization: t } = useAuthUI();
const { actions, state } = useController(createChangePasswordController);
</script>

<template>
    <AuthCard :headingLevel="2" :title="t.changePassword">
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.submit">
            <FormBanner :error="state.formError" :success="state.successMessage" />
            <Field
                :field="state.fields.currentPassword"
                :label="t.currentPasswordLabel"
                name="currentPassword"
                type="password"
                autoComplete="current-password"
                @blur="actions.blur('currentPassword')"
                @change="actions.setField('currentPassword', $event)"
            />
            <Field
                :field="state.fields.newPassword"
                :label="t.newPasswordLabel"
                name="newPassword"
                type="password"
                autoComplete="new-password"
                @blur="actions.blur('newPassword')"
                @change="actions.setField('newPassword', $event)"
            />
            <Field
                :field="state.fields.confirmPassword"
                :label="t.confirmPasswordLabel"
                name="confirmPassword"
                type="password"
                autoComplete="new-password"
                @blur="actions.blur('confirmPassword')"
                @change="actions.setField('confirmPassword', $event)"
            />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.changePassword }}</SubmitButton>
        </form>
    </AuthCard>
</template>
