// registry/auth-ui-svelte/svelte/DeleteAccountCard.svelte
<script lang="ts">
    import { createDeleteAccountController } from "../core/delete-account";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import FormField from "./FormField.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    const t = useAuthUI().localization;
    const { actions, state: form } = controllerStore(createDeleteAccountController);
</script>

<AuthCard description={t.deleteAccountWarning} headingLevel={2} title={t.deleteAccount}>
    <form
        class="lunora-auth-form"
        novalidate
        onsubmit={(event) => {
            event.preventDefault();
            void actions.submit();
        }}
    >
        <FormBanner error={$form.formError} />
        <FormField {actions} autoComplete="current-password" field="password" fields={$form.fields} label={t.passwordLabel} type="password" />
        <SubmitButton pending={$form.status === "submitting"}>{t.deleteAccount}</SubmitButton>
    </form>
</AuthCard>

// packages/auth-ui/src/vue/DeleteAccountCard.vue
<script setup lang="ts">
import { createDeleteAccountController } from "../core/delete-account";
import AuthCard from "./AuthCard.vue";
import FormField from "./FormField.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

const { localization: t } = useAuthUI();
const { actions, state } = useController(createDeleteAccountController);
</script>

<template>
    <AuthCard :title="t.deleteAccount" :description="t.deleteAccountWarning" :headingLevel="2">
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.submit">
            <FormBanner :error="state.formError" />
            <FormField :actions="actions" field="password" :fields="state.fields" :label="t.passwordLabel" type="password" autoComplete="current-password" />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.deleteAccount }}</SubmitButton>
        </form>
    </AuthCard>
</template>
