// registry/auth-ui-svelte/svelte/FormBanner.svelte
<!-- Top-level error / success banner (error is announced via role="alert"). -->
<script lang="ts">
    let {
        error,
        success,
    }: {
        error?: string;
        success?: string;
    } = $props();
</script>

{#if error !== undefined}
    <p class="lunora-auth-banner lunora-auth-banner--error" role="alert">{error}</p>
{:else if success !== undefined}
    <p class="lunora-auth-banner lunora-auth-banner--success" role="status">{success}</p>
{/if}

// packages/auth-ui/src/vue/FormBanner.vue
<script setup lang="ts">
// Top-level error / success banner. Error is announced via `role="alert"`,
// success via `role="status"`. Error takes precedence when both are set.
defineProps<{
    error?: string;
    success?: string;
}>();
</script>

<template>
    <p v-if="error !== undefined" class="lunora-auth-banner lunora-auth-banner--error" role="alert">{{ error }}</p>
    <p v-else-if="success !== undefined" class="lunora-auth-banner lunora-auth-banner--success" role="status">{{ success }}</p>
</template>
