// packages/auth-ui/src/svelte/MagicLinkCard.svelte
<script lang="ts">
    import { isFlowEnabled } from "../core/flow-gate";
    import { createMagicLinkController } from "../core/magic-link";
    import AuthCard from "./AuthCard.svelte";
    import AuthLink from "./AuthLink.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import Field from "./Field.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    let { signInHref = "/sign-in" }: { signInHref?: string } = $props();

    const context = useAuthUI();
    const t = context.localization;
    const enabled = isFlowEnabled(context, "magicLink", "MagicLinkCard");
    const { actions, state: form } = controllerStore(createMagicLinkController);
</script>

{#if enabled}
    <AuthCard title={t.magicLink}>
        <form
            class="lunora-auth-form"
            novalidate
            onsubmit={(event) => {
                event.preventDefault();
                void actions.submit();
            }}
        >
            <FormBanner error={$form.formError} success={$form.successMessage} />
            <Field
                autoComplete="email"
                field={$form.fields.email}
                label={t.emailLabel}
                name="email"
                onBlur={() => {
                    actions.blur("email");
                }}
                onChange={(value) => {
                    actions.setField("email", value);
                }}
                type="email"
            />
            <SubmitButton pending={$form.status === "submitting"}>{t.magicLink}</SubmitButton>
        </form>
        {#snippet footer()}
            <AuthLink href={signInHref}>{t.backToSignIn}</AuthLink>
        {/snippet}
    </AuthCard>
{/if}

// packages/auth-ui/src/vue/MagicLinkCard.vue
<script setup lang="ts">
import { isFlowEnabled } from "../core/flow-gate";
import { createMagicLinkController } from "../core/magic-link";
import AuthCard from "./AuthCard.vue";
import AuthLink from "./AuthLink.vue";
import Field from "./Field.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

withDefaults(
    defineProps<{
        signInHref?: string;
    }>(),
    {
        signInHref: "/sign-in",
    },
);

const context = useAuthUI();
const t = context.localization;
const enabled = isFlowEnabled(context, "magicLink", "MagicLinkCard");
const { actions, state } = useController(createMagicLinkController);
</script>

<template>
    <AuthCard v-if="enabled" :title="t.magicLink">
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.submit">
            <FormBanner :error="state.formError" :success="state.successMessage" />
            <Field
                :field="state.fields.email"
                :label="t.emailLabel"
                name="email"
                type="email"
                autoComplete="email"
                @blur="actions.blur('email')"
                @change="actions.setField('email', $event)"
            />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.magicLink }}</SubmitButton>
        </form>
        <template #footer>
            <AuthLink :href="signInHref">{{ t.backToSignIn }}</AuthLink>
        </template>
    </AuthCard>
</template>
