// registry/auth-ui-svelte/svelte/MembersCard.svelte
<script module lang="ts">
    // Per-instance ids: two cards on one page must not collide.
    let counter = 0;
</script>

<script lang="ts">
    import { ROLE_OPTIONS, createMembersController, isFlowEnabled } from "../core";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import FormBanner from "./FormBanner.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    const uid = `lunora-auth-${(counter += 1)}`;
    const context = useAuthUI();
    const t = context.localization;
    const enabled = isFlowEnabled(context, "organization", "MembersCard");
    const { actions, state: res } = controllerStore((context_) => createMembersController(context_, { autoLoad: enabled }));

    let email = $state("");
    let role = $state<string>("member");

    const invite = (): void => {
        if (email.trim() === "") {
            return;
        }

        void actions.invite(email.trim(), role);
        email = "";
    };
</script>

{#if enabled}
    <AuthCard title={t.members}>
        <FormBanner error={$res.error} />

        {#if $res.loading}
            <p class="lunora-auth-card__description">…</p>
        {:else}
            <ul class="lunora-auth-list">
                {#each $res.members as member (member.id ?? member.userId ?? member.user?.email)}
                    <li class="lunora-auth-list__item">
                        <span class="lunora-auth-list__label">
                            {member.user?.email ?? member.user?.name ?? member.userId} · {member.role}
                        </span>
                        {#if member.id !== undefined}
                            <button
                                class="lunora-auth-link"
                                disabled={$res.busy}
                                onclick={() => {
                                    void actions.removeMember(member.id);
                                }}
                                type="button"
                            >
                                {t.remove}
                            </button>
                        {/if}
                    </li>
                {/each}
            </ul>
        {/if}

        {#if $res.invitations.length > 0}
            <p class="lunora-auth-card__description">{t.invitations}</p>
            <ul class="lunora-auth-list">
                {#each $res.invitations as invitation (invitation.id ?? invitation.email)}
                    <li class="lunora-auth-list__item">
                        <span class="lunora-auth-list__label">
                            {invitation.email} · {invitation.role}
                        </span>
                        {#if invitation.id !== undefined}
                            <button
                                class="lunora-auth-link"
                                disabled={$res.busy}
                                onclick={() => {
                                    void actions.cancelInvitation(invitation.id);
                                }}
                                type="button"
                            >
                                {t.cancel}
                            </button>
                        {/if}
                    </li>
                {/each}
            </ul>
        {/if}

        <form
            class="lunora-auth-form"
            novalidate
            onsubmit={(event) => {
                event.preventDefault();
                invite();
            }}
        >
            <div class="lunora-auth-field">
                <label class="lunora-auth-field__label" for="{uid}-invite-email">{t.inviteEmailLabel}</label>
                <input bind:value={email} class="lunora-auth-field__input" id="{uid}-invite-email" type="email" />
            </div>
            <div class="lunora-auth-field">
                <label class="lunora-auth-field__label" for="{uid}-invite-role">{t.roleLabel}</label>
                <select bind:value={role} class="lunora-auth-field__input" id="{uid}-invite-role">
                    {#each ROLE_OPTIONS as option (option)}
                        <option value={option}>{option}</option>
                    {/each}
                </select>
            </div>
            <SubmitButton pending={$res.busy}>{t.inviteMember}</SubmitButton>
        </form>
    </AuthCard>
{/if}

// packages/auth-ui/src/vue/MembersCard.vue
<script setup lang="ts">
import { ref, useId } from "vue";

import { ROLE_OPTIONS, createMembersController, isFlowEnabled } from "../core";
import AuthCard from "./AuthCard.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

const context = useAuthUI();
const t = context.localization;
const enabled = isFlowEnabled(context, "organization", "MembersCard");
// Generated, not hard-coded: two cards on one page must not collide.
const uid = useId();
const roleId = `${uid}-role`;
const { actions, state } = useController((context_) => createMembersController(context_, { autoLoad: enabled }));

const email = ref("");
const role = ref<string>("member");

const invite = (): void => {
    if (email.value.trim() === "") {
        return;
    }

    void actions.invite(email.value.trim(), role.value);
    email.value = "";
};

// Takes the optional id straight from the row: the template can't narrow,
// so the guard lives here rather than as a cast at the call site.
const onRemoveMember = (id?: string): void => {
    if (id !== undefined) {
        void actions.removeMember(id);
    }
};

const onCancelInvitation = (id: string): void => {
    void actions.cancelInvitation(id);
};
</script>

<template>
    <AuthCard v-if="enabled" :title="t.members">
        <FormBanner :error="state.error" />

        <p v-if="state.loading" class="lunora-auth-card__description">…</p>
        <ul v-else class="lunora-auth-list">
            <li v-for="member in state.members" :key="member.id ?? member.userId ?? member.user?.email" class="lunora-auth-list__item">
                <span class="lunora-auth-list__label">{{ member.user?.email ?? member.user?.name ?? member.userId }} · {{ member.role }}</span>
                <button v-if="member.id !== undefined" class="lunora-auth-link" type="button" :disabled="state.busy" @click="onRemoveMember(member.id)">
                    {{ t.remove }}
                </button>
            </li>
        </ul>

        <template v-if="state.invitations.length > 0">
            <p class="lunora-auth-card__description">{{ t.invitations }}</p>
            <ul class="lunora-auth-list">
                <li v-for="invitation in state.invitations" :key="invitation.id ?? invitation.email" class="lunora-auth-list__item">
                    <span class="lunora-auth-list__label">{{ invitation.email }} · {{ invitation.role }}</span>
                    <button
                        v-if="invitation.id !== undefined"
                        class="lunora-auth-link"
                        type="button"
                        :disabled="state.busy"
                        @click="onCancelInvitation(invitation.id)"
                    >
                        {{ t.cancel }}
                    </button>
                </li>
            </ul>
        </template>

        <form class="lunora-auth-form" novalidate @submit.prevent="invite">
            <div class="lunora-auth-field">
                <label class="lunora-auth-field__label" :for="`${uid}-email`">{{ t.inviteEmailLabel }}</label>
                <input :id="`${uid}-email`" v-model="email" class="lunora-auth-field__input" type="email" />
            </div>
            <div class="lunora-auth-field">
                <label class="lunora-auth-field__label" :for="roleId">{{ t.roleLabel }}</label>
                <select :id="roleId" v-model="role" class="lunora-auth-field__input">
                    <option v-for="option in ROLE_OPTIONS" :key="option" :value="option">{{ option }}</option>
                </select>
            </div>
            <SubmitButton :pending="state.busy">{{ t.inviteMember }}</SubmitButton>
        </form>
    </AuthCard>
</template>
