// packages/auth-ui/src/svelte/SignInCard.svelte
<script lang="ts">
    import { createSignInController, signInWithSocial } from "../core";
    import AuthCard from "./AuthCard.svelte";
    import AuthDivider from "./AuthDivider.svelte";
    import AuthLink from "./AuthLink.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import Field from "./Field.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SocialButtons from "./SocialButtons.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    let {
        forgotPasswordHref = "/forgot-password",
        signUpHref = "/sign-up",
    }: {
        forgotPasswordHref?: string;
        signUpHref?: string;
    } = $props();

    const context = useAuthUI();
    const t = context.localization;
    const social = context.social;
    const { actions, state: form } = controllerStore(createSignInController);
</script>

<AuthCard title={t.signIn}>
    <SocialButtons
        onSelect={(provider) => {
            void signInWithSocial(context, provider);
        }}
        providers={social}
    />
    {#if social.length > 0}
        <AuthDivider />
    {/if}
    <form
        class="lunora-auth-form"
        novalidate
        onsubmit={(event) => {
            event.preventDefault();
            void actions.submit();
        }}
    >
        <FormBanner error={$form.formError} />
        <Field
            autoComplete="email"
            field={$form.fields.email}
            label={t.emailLabel}
            name="email"
            onBlur={() => {
                actions.blur("email");
            }}
            onChange={(value) => {
                actions.setField("email", value);
            }}
            type="email"
        />
        <Field
            autoComplete="current-password"
            field={$form.fields.password}
            label={t.passwordLabel}
            name="password"
            onBlur={() => {
                actions.blur("password");
            }}
            onChange={(value) => {
                actions.setField("password", value);
            }}
            type="password"
        />
        <AuthLink href={forgotPasswordHref}>{t.forgotPasswordLink}</AuthLink>
        <SubmitButton pending={$form.status === "submitting"}>{t.signIn}</SubmitButton>
    </form>
    {#snippet footer()}
        <AuthLink href={signUpHref}>{t.noAccount}</AuthLink>
    {/snippet}
</AuthCard>

// packages/auth-ui/src/vue/SignInCard.vue
<script setup lang="ts">
import { createSignInController } from "../core/sign-in";
import { signInWithSocial } from "../core/social";
import AuthCard from "./AuthCard.vue";
import AuthDivider from "./AuthDivider.vue";
import AuthLink from "./AuthLink.vue";
import Field from "./Field.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SocialButtons from "./SocialButtons.vue";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

withDefaults(
    defineProps<{
        forgotPasswordHref?: string;
        signUpHref?: string;
    }>(),
    {
        forgotPasswordHref: "/forgot-password",
        signUpHref: "/sign-up",
    },
);

const context = useAuthUI();
const t = context.localization;
const social = context.social;
const { actions, state } = useController(createSignInController);

const onSocial = (provider: string): void => {
    void signInWithSocial(context, provider);
};
</script>

<template>
    <AuthCard :title="t.signIn">
        <SocialButtons :providers="social" @select="onSocial" />
        <AuthDivider v-if="social.length > 0" />
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.submit">
            <FormBanner :error="state.formError" />
            <Field
                :field="state.fields.email"
                :label="t.emailLabel"
                name="email"
                type="email"
                autoComplete="email"
                @blur="actions.blur('email')"
                @change="actions.setField('email', $event)"
            />
            <Field
                :field="state.fields.password"
                :label="t.passwordLabel"
                name="password"
                type="password"
                autoComplete="current-password"
                @blur="actions.blur('password')"
                @change="actions.setField('password', $event)"
            />
            <AuthLink :href="forgotPasswordHref">{{ t.forgotPasswordLink }}</AuthLink>
            <SubmitButton :pending="state.status === 'submitting'">{{ t.signIn }}</SubmitButton>
        </form>
        <template #footer>
            <AuthLink :href="signUpHref">{{ t.noAccount }}</AuthLink>
        </template>
    </AuthCard>
</template>
