// packages/auth-ui/src/svelte/SignUpCard.svelte
<script lang="ts">
    import { createSignUpController } from "../core";
    import AuthCard from "./AuthCard.svelte";
    import AuthLink from "./AuthLink.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import Field from "./Field.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    let { signInHref = "/sign-in" }: { signInHref?: string } = $props();

    const t = useAuthUI().localization;
    const { actions, state: form } = controllerStore(createSignUpController);
</script>

<AuthCard title={t.signUp}>
    <form
        class="lunora-auth-form"
        novalidate
        onsubmit={(event) => {
            event.preventDefault();
            void actions.submit();
        }}
    >
        <FormBanner error={$form.formError} />
        <Field
            autoComplete="name"
            field={$form.fields.name}
            label={t.nameLabel}
            name="name"
            onBlur={() => {
                actions.blur("name");
            }}
            onChange={(value) => {
                actions.setField("name", value);
            }}
        />
        <Field
            autoComplete="email"
            field={$form.fields.email}
            label={t.emailLabel}
            name="email"
            onBlur={() => {
                actions.blur("email");
            }}
            onChange={(value) => {
                actions.setField("email", value);
            }}
            type="email"
        />
        <Field
            autoComplete="new-password"
            field={$form.fields.password}
            label={t.passwordLabel}
            name="password"
            onBlur={() => {
                actions.blur("password");
            }}
            onChange={(value) => {
                actions.setField("password", value);
            }}
            type="password"
        />
        <SubmitButton pending={$form.status === "submitting"}>{t.signUp}</SubmitButton>
    </form>
    {#snippet footer()}
        <AuthLink href={signInHref}>{t.haveAccount}</AuthLink>
    {/snippet}
</AuthCard>

// packages/auth-ui/src/vue/SignUpCard.vue
<script setup lang="ts">
import { createSignUpController } from "../core/sign-up";
import AuthCard from "./AuthCard.vue";
import AuthLink from "./AuthLink.vue";
import Field from "./Field.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

withDefaults(
    defineProps<{
        signInHref?: string;
    }>(),
    {
        signInHref: "/sign-in",
    },
);

const { localization: t } = useAuthUI();
const { actions, state } = useController(createSignUpController);
</script>

<template>
    <AuthCard :title="t.signUp">
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.submit">
            <FormBanner :error="state.formError" />
            <Field
                :field="state.fields.name"
                :label="t.nameLabel"
                name="name"
                autoComplete="name"
                @blur="actions.blur('name')"
                @change="actions.setField('name', $event)"
            />
            <Field
                :field="state.fields.email"
                :label="t.emailLabel"
                name="email"
                type="email"
                autoComplete="email"
                @blur="actions.blur('email')"
                @change="actions.setField('email', $event)"
            />
            <Field
                :field="state.fields.password"
                :label="t.passwordLabel"
                name="password"
                type="password"
                autoComplete="new-password"
                @blur="actions.blur('password')"
                @change="actions.setField('password', $event)"
            />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.signUp }}</SubmitButton>
        </form>
        <template #footer>
            <AuthLink :href="signInHref">{{ t.haveAccount }}</AuthLink>
        </template>
    </AuthCard>
</template>
