// packages/auth-ui/src/svelte/UserInvitationsCard.svelte
<!-- Every invitation waiting for the signed-in user, decidable in place. -->
<script lang="ts">
    import { createUserInvitationsController } from "../core/invitations";
    import { firstLabel, rowActionLabel } from "../core/labels";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import FormBanner from "./FormBanner.svelte";
    import Skeleton from "./Skeleton.svelte";

    const t = useAuthUI().localization;
    const { actions, state: res } = controllerStore(createUserInvitationsController);
</script>

<AuthCard title={t.invitations}>
    <FormBanner error={$res.error} />
    {#if $res.loading}
        <Skeleton rows={2} />
    {:else}
        <ul class="lunora-auth-list">
            {#each $res.items as invitation (invitation.id)}
                <li class="lunora-auth-list__item">
                    <span class="lunora-auth-list__label">{firstLabel(invitation.organizationName, invitation.email)}</span>
                    <span class="lunora-auth-list__actions">
                        <button
                            aria-label={rowActionLabel(t.invitationAccept, firstLabel(invitation.organizationName, invitation.email))}
                            class="lunora-auth-button"
                            disabled={$res.busy}
                            onclick={() => {
                                void actions.accept(invitation.id ?? "");
                            }}
                            type="button"
                        >
                            {t.invitationAccept}
                        </button>
                        <button
                            aria-label={rowActionLabel(t.invitationReject, firstLabel(invitation.organizationName, invitation.email))}
                            class="lunora-auth-button lunora-auth-button--secondary"
                            disabled={$res.busy}
                            onclick={() => {
                                void actions.reject(invitation.id ?? "");
                            }}
                            type="button"
                        >
                            {t.invitationReject}
                        </button>
                    </span>
                </li>
            {/each}
            {#if $res.items.length === 0}
                <li class="lunora-auth-list__empty">{t.invitationsEmpty}</li>
            {/if}
        </ul>
    {/if}
</AuthCard>

// packages/auth-ui/src/vue/UserInvitationsCard.vue
<script setup lang="ts">
// Every invitation waiting for the signed-in user, decidable in place.
import { createUserInvitationsController } from "../core/invitations";
import { firstLabel, rowActionLabel } from "../core/labels";
import AuthCard from "./AuthCard.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import Skeleton from "./Skeleton.vue";
import { useController } from "./use-controller";

const { localization: t } = useAuthUI();
const { actions, state } = useController(createUserInvitationsController);

// Takes the optional id straight from the row: the template can't narrow,
// so the guard lives here rather than as a cast at the call site.
const onAccept = (id?: string): void => {
    void actions.accept(id ?? "");
};

const onReject = (id?: string): void => {
    void actions.reject(id ?? "");
};
</script>

<template>
    <AuthCard :title="t.invitations">
        <FormBanner :error="state.error" />
        <Skeleton v-if="state.loading" :rows="2" />
        <ul v-else class="lunora-auth-list">
            <li v-for="invitation in state.items" :key="invitation.id" class="lunora-auth-list__item">
                <span class="lunora-auth-list__label">{{ firstLabel(invitation.organizationName, invitation.email) }}</span>
                <span class="lunora-auth-list__actions">
                    <button
                        class="lunora-auth-button"
                        type="button"
                        :disabled="state.busy"
                        :aria-label="rowActionLabel(t.invitationAccept, firstLabel(invitation.organizationName, invitation.email))"
                        @click="onAccept(invitation.id)"
                    >
                        {{ t.invitationAccept }}
                    </button>
                    <button
                        class="lunora-auth-button lunora-auth-button--secondary"
                        type="button"
                        :disabled="state.busy"
                        :aria-label="rowActionLabel(t.invitationReject, firstLabel(invitation.organizationName, invitation.email))"
                        @click="onReject(invitation.id)"
                    >
                        {{ t.invitationReject }}
                    </button>
                </span>
            </li>
            <li v-if="state.items.length === 0" class="lunora-auth-list__empty">{{ t.invitationsEmpty }}</li>
        </ul>
    </AuthCard>
</template>
