// packages/auth-ui/src/react/two-factor-setup-card.tsx
"use client";

import type { ReactElement } from "react";

import { isFlowEnabled } from "../core/flow-gate";
import { createTwoFactorSetupController } from "../core/two-factor-setup";
import { AuthCard, Field, FormBanner, SubmitButton } from "./primitives";
import { useAuthUI } from "./provider";
import { useController } from "./use-controller";

const onSubmit =
    (action: () => unknown) =>
    (event: { preventDefault: () => void }): void => {
        event.preventDefault();
        void action();
    };

const TwoFactorSetupCard = (): ReactElement | null => {
    const context = useAuthUI();
    const { localization: t } = context;
    const [state, actions] = useController(createTwoFactorSetupController);
    const pending = state.status === "submitting";

    if (!isFlowEnabled(context, "twoFactor", "TwoFactorSetupCard")) {
        return null;
    }

    if (state.step === "enabled") {
        return (
            <AuthCard title={t.twoFactorSetup}>
                <FormBanner error={state.error} success={t.twoFactorEnabled} />
                <form className="lunora-auth-form" noValidate onSubmit={onSubmit(actions.disable)}>
                    <Field
                        autoComplete="current-password"
                        field={state.password}
                        label={t.passwordLabel}
                        name="password"
                        onBlur={() => undefined}
                        onChange={actions.setPassword}
                        type="password"
                    />
                    <SubmitButton pending={pending}>{t.twoFactorDisable}</SubmitButton>
                </form>
            </AuthCard>
        );
    }

    if (state.step === "verify") {
        return (
            <AuthCard description={t.twoFactorScan} title={t.twoFactorSetup}>
                <FormBanner error={state.error} />
                {state.totpUri === undefined ? null : <code className="lunora-auth-code">{state.totpUri}</code>}
                {state.backupCodes.length === 0 ? null : (
                    <>
                        <p className="lunora-auth-card__description">{t.backupCodes}</p>
                        <ul className="lunora-auth-codes">
                            {state.backupCodes.map((backupCode) => (
                                <li className="lunora-auth-codes__item" key={backupCode}>
                                    {backupCode}
                                </li>
                            ))}
                        </ul>
                    </>
                )}
                <form className="lunora-auth-form" noValidate onSubmit={onSubmit(actions.verify)}>
                    <Field
                        autoComplete="one-time-code"
                        field={state.code}
                        label={t.codeLabel}
                        name="code"
                        onBlur={() => undefined}
                        onChange={actions.setCode}
                    />
                    <SubmitButton pending={pending}>{t.twoFactor}</SubmitButton>
                </form>
            </AuthCard>
        );
    }

    return (
        <AuthCard title={t.twoFactorSetup}>
            <FormBanner error={state.error} />
            <form className="lunora-auth-form" noValidate onSubmit={onSubmit(actions.enable)}>
                <Field
                    autoComplete="current-password"
                    field={state.password}
                    label={t.passwordLabel}
                    name="password"
                    onBlur={() => undefined}
                    onChange={actions.setPassword}
                    type="password"
                />
                <SubmitButton pending={pending}>{t.twoFactorEnable}</SubmitButton>
            </form>
        </AuthCard>
    );
};

export { TwoFactorSetupCard };

// packages/auth-ui/src/solid/two-factor-setup-card.tsx
import type { JSX } from "solid-js";
import { For, Show } from "solid-js";

import { isFlowEnabled } from "../core/flow-gate";
import { createTwoFactorSetupController } from "../core/two-factor-setup";
import { AuthCard, Field, FormBanner, SubmitButton } from "./primitives";
import { useAuthUI } from "./provider";
import { createController } from "./use-controller";

const onSubmit =
    (action: () => unknown) =>
    (event: Event): void => {
        event.preventDefault();
        void action();
    };

const TwoFactorSetupCard = (): JSX.Element => {
    const context = useAuthUI();
    const { localization: t } = context;
    const [state, actions] = createController(createTwoFactorSetupController);

    if (!isFlowEnabled(context, "twoFactor", "TwoFactorSetupCard")) {
        return null;
    }

    return (
        <Show
            fallback={
                <Show
                    fallback={
                        <AuthCard title={t.twoFactorSetup}>
                            <FormBanner error={state.error} />
                            <form class="lunora-auth-form" noValidate onSubmit={onSubmit(actions.enable)}>
                                <Field
                                    autoComplete="current-password"
                                    field={state.password}
                                    label={t.passwordLabel}
                                    name="password"
                                    onBlur={() => undefined}
                                    onChange={actions.setPassword}
                                    type="password"
                                />
                                <SubmitButton pending={state.status === "submitting"}>{t.twoFactorEnable}</SubmitButton>
                            </form>
                        </AuthCard>
                    }
                    when={state.step === "verify"}
                >
                    <AuthCard description={t.twoFactorScan} title={t.twoFactorSetup}>
                        <FormBanner error={state.error} />
                        <Show when={state.totpUri !== undefined}>
                            <code class="lunora-auth-code">{state.totpUri}</code>
                        </Show>
                        <Show when={state.backupCodes.length > 0}>
                            <p class="lunora-auth-card__description">{t.backupCodes}</p>
                            <ul class="lunora-auth-codes">
                                <For each={state.backupCodes}>{(backupCode) => <li class="lunora-auth-codes__item">{backupCode}</li>}</For>
                            </ul>
                        </Show>
                        <form class="lunora-auth-form" noValidate onSubmit={onSubmit(actions.verify)}>
                            <Field
                                autoComplete="one-time-code"
                                field={state.code}
                                label={t.codeLabel}
                                name="code"
                                onBlur={() => undefined}
                                onChange={actions.setCode}
                            />
                            <SubmitButton pending={state.status === "submitting"}>{t.twoFactor}</SubmitButton>
                        </form>
                    </AuthCard>
                </Show>
            }
            when={state.step === "enabled"}
        >
            <AuthCard title={t.twoFactorSetup}>
                <FormBanner error={state.error} success={t.twoFactorEnabled} />
                <form class="lunora-auth-form" noValidate onSubmit={onSubmit(actions.disable)}>
                    <Field
                        autoComplete="current-password"
                        field={state.password}
                        label={t.passwordLabel}
                        name="password"
                        onBlur={() => undefined}
                        onChange={actions.setPassword}
                        type="password"
                    />
                    <SubmitButton pending={state.status === "submitting"}>{t.twoFactorDisable}</SubmitButton>
                </form>
            </AuthCard>
        </Show>
    );
};

export { TwoFactorSetupCard };
