// registry/auth-ui-angular/angular/user-button.ts
/**
 * The signed-in-user chrome, mirroring the React `user-button.tsx` 1:1: the
 * avatar (photo or initials), the avatar + name + email block, and the avatar
 * menu with sign-out.
 */
import type { ElementRef, Signal } from "@angular/core";
import { ChangeDetectionStrategy, Component, computed, input, linkedSignal, signal, viewChild } from "@angular/core";

import type { SessionActions, SessionState } from "../core/session";
import { createSessionController, userInitials, userLabel } from "../core/session";
import { signOut } from "../core/session-actions";
import type { AuthUser } from "../core/types";
import { controllerSignal } from "./controller-signal";
import { injectAuthUIContext } from "./provider";

/**
 * A user's photo, or their initials when there isn't one.
 *
 * The image is the only thing here that can fail at runtime, so a broken URL
 * falls back to the initials rather than to a browser's broken-image glyph —
 * `user.image` is a plain string column an app can put anything in.
 */
@Component({
    changeDetection: ChangeDetectionStrategy.OnPush,
    selector: "lunora-user-avatar",
    standalone: true,
    template: `
        @if (showImage()) {
            <img class="lunora-auth-avatar" alt="" [src]="user()?.image" [style.height.px]="size()" [style.width.px]="size()" (error)="failed.set(true)" />
        } @else {
            <span class="lunora-auth-avatar lunora-auth-avatar--initials" aria-hidden="true" [style.height.px]="size()" [style.width.px]="size()">
                {{ initials() }}
            </span>
        }
    `,
})
class UserAvatarComponent {
    readonly size = input(32);
    readonly user = input<AuthUser>();

    /*
     * A new user means a new image URL, so a previous failure must not stick to
     * it. `linkedSignal` is Angular's version of React's adjust-state-during-render
     * pattern: the flag is writable, and resets itself whenever the URL it
     * describes changes.
     */
    protected readonly failed = linkedSignal<string | undefined, boolean>({
        computation: () => false,
        source: () => this.user()?.image,
    });

    protected readonly initials = computed(() => userInitials(this.user()));
    protected readonly showImage = computed(() => {
        const image = this.user()?.image;

        return image !== undefined && image !== "" && !this.failed();
    });
}

/** Avatar + name + email, the block that identifies an account in a list or menu. */
@Component({
    changeDetection: ChangeDetectionStrategy.OnPush,
    imports: [UserAvatarComponent],
    selector: "lunora-user-view",
    standalone: true,
    template: `
        <span class="lunora-auth-user">
            <lunora-user-avatar [size]="compact() ? 24 : 36" [user]="user()" />
            <span class="lunora-auth-user__text">
                <span class="lunora-auth-user__name">{{ label() }}</span>
                @if (!compact() && user()?.email !== undefined) {
                    <span class="lunora-auth-user__email">{{ user()?.email }}</span>
                }
            </span>
        </span>
    `,
})
class UserViewComponent {
    /** Hide the email line, for tight rows. */
    readonly compact = input(false);
    readonly user = input<AuthUser>();

    protected readonly label = computed(() => userLabel(this.user()));
}

let menuIdCounter = 0;

/**
 * The avatar menu: who is signed in, plus sign-out and whatever the app hangs
 * off it.
 *
 * It is a disclosure rather than a `<menu>` because its contents are app-defined
 * — links, an organization switcher, a theme row — and forcing those into menu
 * item semantics would mislabel them. Escape and outside-click close it, and
 * focus returns to the trigger, which is the part hand-rolled dropdowns usually
 * miss.
 *
 * Extra rows are projected: anything between the tags renders above sign-out.
 */
@Component({
    changeDetection: ChangeDetectionStrategy.OnPush,
    host: {
        "(document:keydown.escape)": "onEscape()",
        "(document:mousedown)": "onPointerDown($event)",
    },
    imports: [UserAvatarComponent, UserViewComponent],
    selector: "lunora-user-button",
    standalone: true,
    template: `
        <!--
          "Not asked yet" and "asked, nobody home" look identical in the user
          field, and rendering a sign-in link during the first request makes
          every page flash one. "settled" is the difference.
        -->
        @if (!session().settled) {
            <span class="lunora-auth-userbutton lunora-auth-userbutton--loading"></span>
        } @else if (!session().user) {
            @if (!hideWhenSignedOut()) {
                <a class="lunora-auth-link" [href]="signInHref()">{{ t.signIn }}</a>
            }
        } @else {
            <div class="lunora-auth-userbutton" #root>
                <button
                    class="lunora-auth-userbutton__trigger"
                    type="button"
                    #trigger
                    aria-haspopup="true"
                    [attr.aria-controls]="open() ? menuId : null"
                    [attr.aria-expanded]="open()"
                    [attr.aria-label]="userLabel(session().user)"
                    (click)="open.set(!open())"
                >
                    <lunora-user-avatar [user]="session().user" />
                </button>
                @if (open()) {
                    <div class="lunora-auth-userbutton__menu" [id]="menuId">
                        <div class="lunora-auth-userbutton__header">
                            <lunora-user-view [user]="session().user" />
                        </div>
                        <ng-content />
                        <button class="lunora-auth-button lunora-auth-button--secondary" type="button" (click)="signOut()">{{ t.signOut }}</button>
                    </div>
                }
            </div>
        }
    `,
})
class UserButtonComponent {
    /** Render nothing at all when signed out, instead of a sign-in link. */
    readonly hideWhenSignedOut = input(false);

    // Per-instance id: two buttons on one page must not collide.
    protected readonly menuId = `lunora-auth-userbutton-${(menuIdCounter += 1)}`;
    private readonly context = injectAuthUIContext();
    protected readonly t = this.context().localization;
    private readonly bridge = controllerSignal(createSessionController, { context: this.context });
    protected readonly session: Signal<SessionState> = this.bridge.state;
    private readonly actions: SessionActions = this.bridge.actions;

    protected readonly open = signal(false);
    protected readonly signInHref = computed(() => this.context().redirects.signIn);

    private readonly root = viewChild<ElementRef<HTMLElement>>("root");
    private readonly trigger = viewChild<ElementRef<HTMLButtonElement>>("trigger");

    /** Delegates to the shared helper — Angular templates can only call members. */
    protected readonly userLabel = userLabel;

    protected onEscape(): void {
        if (!this.open()) {
            return;
        }

        this.open.set(false);
        this.trigger()?.nativeElement.focus();
    }

    protected onPointerDown(event: MouseEvent): void {
        const root = this.root()?.nativeElement;

        if (this.open() && root && !root.contains(event.target as Node)) {
            // Focus is deliberately left alone: a click elsewhere is the user
            // moving on, and yanking it back to the trigger would fight them for it.
            this.open.set(false);
        }
    }

    protected signOut(): void {
        this.open.set(false);
        void signOut(this.context()).then(this.actions.refetch);
    }
}

export { UserAvatarComponent, UserButtonComponent, UserViewComponent };

// packages/auth-ui/src/solid/user-button.tsx
import type { JSX } from "solid-js";
import { createEffect, createSignal, createUniqueId, on, onCleanup, Show } from "solid-js";

import { createSessionController, userInitials, userLabel } from "../core/session";
import { signOut } from "../core/session-actions";
import type { AuthUser } from "../core/types";
import { useAuthUI } from "./provider";
import { createController } from "./use-controller";

/**
 * A user's photo, or their initials when there isn't one.
 *
 * The image is the only thing here that can fail at runtime, so a broken URL
 * falls back to the initials rather than to a browser's broken-image glyph —
 * `user.image` is a plain string column an app can put anything in.
 */
interface UserAvatarProps {
    size?: number;
    user?: AuthUser;
}

const UserAvatar = (props: UserAvatarProps): JSX.Element => {
    const [failed, setFailed] = createSignal(false);
    const image = (): string | undefined => props.user?.image;

    // A new user means a new image URL, so a previous failure must not stick to
    // it. Deferred, because the initial run would only re-clear a fresh signal.
    createEffect(
        on(
            image,
            () => {
                setFailed(false);
            },
            { defer: true },
        ),
    );

    const style = (): JSX.CSSProperties => {
        const size = props.size ?? 32;

        return { height: `${size}px`, width: `${size}px` };
    };

    const source = (): string | undefined => {
        const value = image();

        return value === undefined || value === "" || failed() ? undefined : value;
    };

    return (
        <Show
            fallback={
                <span aria-hidden="true" class="lunora-auth-avatar lunora-auth-avatar--initials" style={style()}>
                    {userInitials(props.user)}
                </span>
            }
            when={source()}
        >
            {/* `Show` hands the narrowed URL to the callback — no cast needed. */}
            {(url) => (
                <img
                    alt=""
                    class="lunora-auth-avatar"
                    onError={() => {
                        setFailed(true);
                    }}
                    src={url()}
                    style={style()}
                />
            )}
        </Show>
    );
};

/** Avatar + name + email, the block that identifies an account in a list or menu. */
interface UserViewProps {
    /** Hide the email line, for tight rows. */
    compact?: boolean;
    user?: AuthUser;
}

const UserView = (props: UserViewProps): JSX.Element => (
    <span class="lunora-auth-user">
        <UserAvatar size={props.compact === true ? 24 : 36} user={props.user} />
        <span class="lunora-auth-user__text">
            <span class="lunora-auth-user__name">{userLabel(props.user)}</span>
            <Show when={props.compact !== true && props.user?.email !== undefined}>
                <span class="lunora-auth-user__email">{props.user?.email}</span>
            </Show>
        </span>
    </span>
);

/**
 * The avatar menu: who is signed in, plus sign-out and whatever the app hangs
 * off it.
 *
 * It is a disclosure rather than a `<menu>` because its contents are app-defined
 * — links, an organization switcher, a theme row — and forcing those into menu
 * item semantics would mislabel them. Escape and outside-click close it, and
 * focus returns to the trigger, which is the part hand-rolled dropdowns usually
 * miss.
 */
interface UserButtonProps {
    /** Extra rows rendered above sign-out (links, an org switcher, …). */
    children?: JSX.Element;
    /** Render nothing at all when signed out, instead of a sign-in link. */
    hideWhenSignedOut?: boolean;
}

const UserButton = (props: UserButtonProps): JSX.Element => {
    const context = useAuthUI();
    const { localization: t } = context;
    const [session, sessionActions] = createController(createSessionController);
    const [open, setOpen] = createSignal(false);
    const menuId = createUniqueId();
    let root: HTMLDivElement | undefined;
    let trigger: HTMLButtonElement | undefined;

    const close = (): void => {
        setOpen(false);
        trigger?.focus();
    };

    createEffect(() => {
        if (!open()) {
            return;
        }

        const onKeyDown = (event: KeyboardEvent): void => {
            if (event.key === "Escape") {
                close();
            }
        };

        const onPointerDown = (event: MouseEvent): void => {
            if (root && !root.contains(event.target as Node)) {
                // Not `close()`: a click elsewhere is the user moving on, and
                // yanking focus back to the trigger would fight them for it.
                setOpen(false);
            }
        };

        document.addEventListener("keydown", onKeyDown);
        document.addEventListener("mousedown", onPointerDown);

        onCleanup(() => {
            document.removeEventListener("keydown", onKeyDown);
            document.removeEventListener("mousedown", onPointerDown);
        });
    });

    return (
        // "Not asked yet" and "asked, nobody home" look identical in `user`, and
        // rendering a sign-in link during the first request makes every page
        // flash one. `settled` is the difference.
        <Show fallback={<span class="lunora-auth-userbutton lunora-auth-userbutton--loading" />} when={session.settled}>
            <Show
                fallback={
                    <Show when={props.hideWhenSignedOut !== true}>
                        <a class="lunora-auth-link" href={context.redirects.signIn}>
                            {t.signIn}
                        </a>
                    </Show>
                }
                when={session.user}
            >
                {/* `Show` hands the narrowed user to the callback — no cast needed. */}
                {(user) => (
                    <div class="lunora-auth-userbutton" ref={root}>
                        <button
                            aria-controls={open() ? menuId : undefined}
                            aria-expanded={open()}
                            aria-haspopup="true"
                            aria-label={userLabel(user())}
                            class="lunora-auth-userbutton__trigger"
                            onClick={() => {
                                setOpen((value) => !value);
                            }}
                            ref={trigger}
                            type="button"
                        >
                            <UserAvatar user={user()} />
                        </button>
                        <Show when={open()}>
                            <div class="lunora-auth-userbutton__menu" id={menuId}>
                                <div class="lunora-auth-userbutton__header">
                                    <UserView user={user()} />
                                </div>
                                {props.children}
                                <button
                                    class="lunora-auth-button lunora-auth-button--secondary"
                                    onClick={() => {
                                        setOpen(false);
                                        void signOut(context).then(sessionActions.refetch);
                                    }}
                                    type="button"
                                >
                                    {t.signOut}
                                </button>
                            </div>
                        </Show>
                    </div>
                )}
            </Show>
        </Show>
    );
};

export type { UserAvatarProps, UserButtonProps, UserViewProps };
export { UserAvatar, UserButton, UserView };
