// packages/auth-ui/src/solid/use-controller.ts
import { onCleanup } from "solid-js";
import { createStore, reconcile } from "solid-js/store";

import type { Controller, ControllerContext } from "../core";
import { useAuthUI } from "./provider";

/**
 * Bind any core {@link Controller} to Solid. The controller is created once when
 * the calling component mounts, its state is mirrored into a `createStore` (so
 * reads are fine-grained and only the touched fields re-render), and it's
 * disposed on cleanup. This one function is the entire Solid↔core seam — every
 * card uses it.
 *
 * Unlike the React `useController` there is no dependency array: a Solid
 * component body runs once, so any options the factory closes over are captured
 * at creation. Cards that need to react to changing props should be re-keyed by
 * the caller (`<Show keyed>` / a `key` on the route) instead.
 * @param create Builds the controller from the resolved context.
 */
const createController = <TState extends object, TActions>(create: (context: ControllerContext) => Controller<TState, TActions>): [TState, TActions] => {
    const context = useAuthUI();
    const controller = create(context);

    const [state, setState] = createStore<TState>(controller.getState());

    const unsubscribe = controller.subscribe(() => {
        // `reconcile` diffs the fresh snapshot against the store so Solid only
        // notifies the fields that actually changed — mirrors the granularity of
        // React's `useSyncExternalStore` selector without a manual selector.
        setState(reconcile(controller.getState()));
    });

    onCleanup(() => {
        unsubscribe();
        controller.destroy();
    });

    return [state, controller.actions];
};

export { createController };

// packages/auth-ui/src/react/use-controller.ts
"use client";

import type { DependencyList } from "react";
import { useEffect, useMemo, useSyncExternalStore } from "react";

import type { Controller, ControllerContext } from "../core";
import { useAuthUI } from "./provider";

/**
 * Bind any core {@link Controller} to React. The controller is created once per
 * `[context, ...deps]` (so form state survives re-renders), its state is read
 * through `useSyncExternalStore`, and it's disposed on unmount. This one generic
 * hook is the entire React↔core seam — every card uses it.
 * @param factory Creates the controller from the resolved context. Pass `deps`
 * for any options it closes over (e.g. a reset token) so it re-creates only
 * when those change.
 */
const useController = <TState, TActions>(
    factory: (context: ControllerContext) => Controller<TState, TActions>,
    deps: DependencyList = [],
): [TState, TActions] => {
    const context = useAuthUI();

    const controller = useMemo(
        () => factory(context),

        [context, ...deps],
    );

    const state = useSyncExternalStore(controller.subscribe, controller.getState, controller.getState);

    useEffect(() => controller.destroy, [controller]);

    return [state, controller.actions];
};

export { useController };
