// registry/auth-ui-solid-v2/solid-v2/verify-invite-cards.tsx
import type { JSX } from "@solidjs/web";
import { For, Show } from "solid-js";

import { queryParameter } from "../core/browser-location";
import { createAcceptInvitationController, createUserInvitationsController } from "../core/invitations";
import { rowActionLabel } from "../core/labels";
import { createResendVerificationController, createVerifyEmailController } from "../core/verify-email";
import { FormField, onSubmit } from "./form";
import { AuthCard, FormBanner, Skeleton, SubmitButton } from "./primitives";
import { useAuthUI } from "./provider";
import { createController } from "./use-controller";

/**
 * The page the verification link lands on. It consumes the token on mount and
 * redirects, so the only states a user sees are "working" and "that link is no
 * longer good".
 */
interface VerifyEmailCardProps {
    /** Defaults to `?token=` from the URL. */
    token?: string;
}

const VerifyEmailCard = (props: VerifyEmailCardProps = {}): JSX.Element => {
    const { localization: t } = useAuthUI();
    const [state, actions] = createController((context) => createVerifyEmailController(context, { token: props.token ?? queryParameter("token") }));

    return (
        <AuthCard title={t.verifyEmail}>
            <FormBanner error={state.error} />
            <Show when={state.status === "submitting" || state.status === "idle"}>
                <p class="lunora-auth-note">{t.verifyEmailVerifying}</p>
            </Show>
            <Show when={state.status === "error"}>
                <button
                    class="lunora-auth-button lunora-auth-button--secondary"
                    onClick={() => {
                        void actions.verify();
                    }}
                    type="button"
                >
                    {t.verifyEmailRetry}
                </button>
            </Show>
        </AuthCard>
    );
};

/** Request a fresh verification link — the companion to `VerifyEmailCard`. */
const ResendVerificationCard = (): JSX.Element => {
    const { localization: t } = useAuthUI();
    const [state, actions] = createController(createResendVerificationController);

    return (
        <AuthCard title={t.verifyEmail}>
            <form class="lunora-auth-form" novalidate onSubmit={onSubmit(actions.submit)}>
                <FormBanner error={state.formError} success={state.successMessage} />
                <FormField actions={actions} autoComplete="email" field="email" label={t.emailLabel} state={state} type="email" />
                <SubmitButton pending={state.status === "submitting"}>{t.verifyEmailResend}</SubmitButton>
            </form>
        </AuthCard>
    );
};

/**
 * The screen an organization invitation link lands on.
 *
 * It renders the organization's name before asking for a decision — an "Accept"
 * button with nothing above it is not consent — and bounces through sign-in when
 * there is no session, returning to this same invitation afterwards.
 */
interface AcceptInvitationCardProps {
    /** Defaults to `?invitationId=` from the URL. */
    invitationId?: string;
}

const AcceptInvitationCard = (props: AcceptInvitationCardProps = {}): JSX.Element => {
    const { localization: t } = useAuthUI();
    const [state, actions] = createController((context) =>
        createAcceptInvitationController(context, { invitationId: props.invitationId ?? queryParameter("invitationId") }),
    );

    return (
        <AuthCard description={state.invitation?.organizationName} title={t.invitationTitle}>
            <FormBanner error={state.error} />
            <Show fallback={<Skeleton rows={2} />} when={!state.loading}>
                <div class="lunora-auth-actions">
                    <button
                        class="lunora-auth-button"
                        disabled={state.status === "submitting" || state.invitation === undefined}
                        onClick={() => {
                            void actions.accept();
                        }}
                        type="button"
                    >
                        {t.invitationAccept}
                    </button>
                    <button
                        class="lunora-auth-button lunora-auth-button--secondary"
                        disabled={state.status === "submitting" || state.invitation === undefined}
                        onClick={() => {
                            void actions.reject();
                        }}
                        type="button"
                    >
                        {t.invitationReject}
                    </button>
                </div>
            </Show>
        </AuthCard>
    );
};

/** Every invitation waiting for the signed-in user, decidable in place. */
const UserInvitationsCard = (): JSX.Element => {
    const { localization: t } = useAuthUI();
    const [state, actions] = createController(createUserInvitationsController);

    return (
        <AuthCard title={t.invitations}>
            <FormBanner error={state.error} />
            <Show fallback={<Skeleton rows={2} />} when={!state.loading}>
                <ul class="lunora-auth-list">
                    <For each={state.items}>
                        {(invitation) => (
                            <li class="lunora-auth-list__item">
                                <span class="lunora-auth-list__label">{invitation.organizationName ?? invitation.email}</span>
                                <span class="lunora-auth-list__actions">
                                    <button
                                        aria-label={rowActionLabel(t.invitationAccept, invitation.organizationName ?? invitation.email)}
                                        class="lunora-auth-button"
                                        disabled={state.busy}
                                        onClick={() => {
                                            void actions.accept(invitation.id ?? "");
                                        }}
                                        type="button"
                                    >
                                        {t.invitationAccept}
                                    </button>
                                    <button
                                        aria-label={rowActionLabel(t.invitationReject, invitation.organizationName ?? invitation.email)}
                                        class="lunora-auth-button lunora-auth-button--secondary"
                                        disabled={state.busy}
                                        onClick={() => {
                                            void actions.reject(invitation.id ?? "");
                                        }}
                                        type="button"
                                    >
                                        {t.invitationReject}
                                    </button>
                                </span>
                            </li>
                        )}
                    </For>
                    <Show when={state.items.length === 0}>
                        <li class="lunora-auth-list__empty">{t.invitationsEmpty}</li>
                    </Show>
                </ul>
            </Show>
        </AuthCard>
    );
};

export type { AcceptInvitationCardProps, VerifyEmailCardProps };
export { AcceptInvitationCard, ResendVerificationCard, UserInvitationsCard, VerifyEmailCard };

// packages/auth-ui/src/react/verify-invite-cards.tsx
"use client";

import type { ReactElement } from "react";

import { queryParameter } from "../core/browser-location";
import { createAcceptInvitationController, createUserInvitationsController } from "../core/invitations";
import { rowActionLabel } from "../core/labels";
import { createResendVerificationController, createVerifyEmailController } from "../core/verify-email";
import { FormField } from "./form";
import { onSubmit } from "./on-submit";
import { AuthCard, FormBanner, Skeleton, SubmitButton } from "./primitives";
import { useAuthUI } from "./provider";
import { useController } from "./use-controller";

/**
 * The page the verification link lands on.
 *
 * It consumes the token on mount and redirects, so the only states a user sees
 * are "working" and "that link is no longer good".
 */
interface VerifyEmailCardProps {
    /** Defaults to `?token=` from the URL. */
    token?: string;
}

const VerifyEmailCard = ({ token }: VerifyEmailCardProps = {}): ReactElement => {
    const { localization: t } = useAuthUI();
    const resolved = token ?? queryParameter("token");
    const [state, actions] = useController((context) => createVerifyEmailController(context, { token: resolved }), [resolved]);

    return (
        <AuthCard title={t.verifyEmail}>
            <FormBanner error={state.error} />
            {state.status === "submitting" || state.status === "idle" ? <p className="lunora-auth-note">{t.verifyEmailVerifying}</p> : null}
            {state.status === "error" ? (
                <button
                    className="lunora-auth-button lunora-auth-button--secondary"
                    onClick={() => {
                        void actions.verify();
                    }}
                    type="button"
                >
                    {t.verifyEmailRetry}
                </button>
            ) : null}
        </AuthCard>
    );
};

/** Request a fresh verification link — the companion to {@link VerifyEmailCard}. */
const ResendVerificationCard = (): ReactElement => {
    const { localization: t } = useAuthUI();
    const [state, actions] = useController(createResendVerificationController);

    return (
        <AuthCard title={t.verifyEmail}>
            <form className="lunora-auth-form" noValidate onSubmit={onSubmit(actions.submit)}>
                <FormBanner error={state.formError} success={state.successMessage} />
                <FormField actions={actions} autoComplete="email" field="email" label={t.emailLabel} state={state} type="email" />
                <SubmitButton pending={state.status === "submitting"}>{t.verifyEmailResend}</SubmitButton>
            </form>
        </AuthCard>
    );
};

/**
 * The screen an organization invitation link lands on.
 *
 * It renders the organization's name before asking for a decision — an "Accept"
 * button with nothing above it is not consent — and bounces through sign-in when
 * there is no session, returning to this same invitation afterwards.
 */
interface AcceptInvitationCardProps {
    /** Defaults to `?invitationId=` from the URL. */
    invitationId?: string;
}

const AcceptInvitationCard = ({ invitationId }: AcceptInvitationCardProps = {}): ReactElement => {
    const { localization: t } = useAuthUI();
    const resolved = invitationId ?? queryParameter("invitationId");
    const [state, actions] = useController((context) => createAcceptInvitationController(context, { invitationId: resolved }), [resolved]);

    const organization = state.invitation?.organizationName;

    return (
        <AuthCard description={organization} title={t.invitationTitle}>
            <FormBanner error={state.error} />
            {state.loading ? (
                <Skeleton rows={2} />
            ) : (
                <div className="lunora-auth-actions">
                    <button
                        className="lunora-auth-button"
                        disabled={state.status === "submitting" || state.invitation === undefined}
                        onClick={() => {
                            void actions.accept();
                        }}
                        type="button"
                    >
                        {t.invitationAccept}
                    </button>
                    <button
                        className="lunora-auth-button lunora-auth-button--secondary"
                        disabled={state.status === "submitting" || state.invitation === undefined}
                        onClick={() => {
                            void actions.reject();
                        }}
                        type="button"
                    >
                        {t.invitationReject}
                    </button>
                </div>
            )}
        </AuthCard>
    );
};

/** Every invitation waiting for the signed-in user, decidable in place. */
const UserInvitationsCard = (): ReactElement => {
    const { localization: t } = useAuthUI();
    const [state, actions] = useController(createUserInvitationsController);

    return (
        <AuthCard title={t.invitations}>
            <FormBanner error={state.error} />
            {state.loading ? (
                <Skeleton rows={2} />
            ) : (
                <ul className="lunora-auth-list">
                    {state.items.map((invitation) => (
                        <li className="lunora-auth-list__item" key={invitation.id}>
                            <span className="lunora-auth-list__label">{invitation.organizationName ?? invitation.email}</span>
                            <span className="lunora-auth-list__actions">
                                <button
                                    aria-label={rowActionLabel(t.invitationAccept, invitation.organizationName ?? invitation.email)}
                                    className="lunora-auth-button"
                                    disabled={state.busy}
                                    onClick={() => {
                                        void actions.accept(invitation.id ?? "");
                                    }}
                                    type="button"
                                >
                                    {t.invitationAccept}
                                </button>
                                <button
                                    aria-label={rowActionLabel(t.invitationReject, invitation.organizationName ?? invitation.email)}
                                    className="lunora-auth-button lunora-auth-button--secondary"
                                    disabled={state.busy}
                                    onClick={() => {
                                        void actions.reject(invitation.id ?? "");
                                    }}
                                    type="button"
                                >
                                    {t.invitationReject}
                                </button>
                            </span>
                        </li>
                    ))}
                    {state.items.length === 0 ? <li className="lunora-auth-list__empty">{t.invitationsEmpty}</li> : null}
                </ul>
            )}
        </AuthCard>
    );
};

export type { AcceptInvitationCardProps, VerifyEmailCardProps };
export { AcceptInvitationCard, ResendVerificationCard, UserInvitationsCard, VerifyEmailCard };
