// packages/auth-ui/src/vue/AuthLink.vue
<script setup lang="ts">
import { useAuthUILink } from "./provider";

// Internal link using the provider's framework `Link` component when present,
// else a plain `<a>`.
defineProps<{
    href: string;
}>();

const Link = useAuthUILink();
</script>

<template>
    <component :is="Link" v-if="Link" class="lunora-auth-link" :href="href">
        <slot />
    </component>
    <a v-else class="lunora-auth-link" :href="href">
        <slot />
    </a>
</template>

// registry/auth-ui-svelte/svelte/AuthLink.svelte
<!-- Internal link using the provider's framework `Link` when present, else <a>. -->
<script lang="ts">
    import type { Snippet } from "svelte";

    import { useAuthUILink } from "./context";

    let {
        children,
        href,
    }: {
        children: Snippet;
        href: string;
    } = $props();

    const Link = useAuthUILink();
</script>

{#if Link}
    <Link class="lunora-auth-link" {href}>{@render children()}</Link>
{:else}
    <a class="lunora-auth-link" {href}>{@render children()}</a>
{/if}
