// packages/auth-ui/src/vue/ErrorToaster.vue
<script setup lang="ts">
// The errors that have no card to land in — a failed social redirect, a failed
// unlink, a sign-out that didn't. Mount it once in your app shell.
//
// Errors that *do* belong to a card still render on that card's banner and never
// reach here, so nothing is announced twice.
import { onScopeDispose, shallowRef } from "vue";

import { dismissToast, getToasts, subscribeToasts } from "../core/toast";

// The store is module-level (see `core/toast.ts`), so this is the same
// subscribe-and-copy shape `useController` uses — shallow because the list is
// replaced wholesale on every push, never mutated in place.
const toasts = shallowRef(getToasts());

const unsubscribe = subscribeToasts(() => {
    toasts.value = getToasts();
});

onScopeDispose(unsubscribe);

const onDismiss = (id: number): void => {
    dismissToast(id);
};
</script>

<template>
    <!--
        `polite`, not `assertive`: these are failures the user can retry, not
        something that should interrupt a screen reader mid-sentence.

        Mounted unconditionally — including with no toasts yet. A live region
        only announces changes made AFTER it exists in the accessibility tree;
        gating the whole `<div>` on `toasts.length > 0` meant the very first
        toast landed before assistive tech was watching the region, so it went
        unannounced.
    -->
    <div class="lunora-auth-toaster" aria-live="polite">
        <div v-for="toast in toasts" :key="toast.id" class="lunora-auth-toast" role="status">
            <span class="lunora-auth-toast__message">{{ toast.message }}</span>
            <button class="lunora-auth-toast__dismiss" type="button" aria-label="Dismiss" @click="onDismiss(toast.id)">×</button>
        </div>
    </div>
</template>

// registry/auth-ui-svelte/svelte/ErrorToaster.svelte
<!--
    Renders the errors that have no card to land in — a failed social redirect, a
    failed unlink, a sign-out that didn't. Mount it once in your app shell.

    Errors that *do* belong to a card still render on that card's banner and never
    reach here, so nothing is announced twice.
-->
<script lang="ts">
    import type { Toast } from "../core/toast";
    import { dismissToast, getToasts, subscribeToasts } from "../core/toast";

    /*
     * The store is module-level (see `core/toast.ts`), not a controller bound to
     * the provider, so this mirrors it into local state rather than going through
     * `controllerStore`.
     */
    let toasts = $state<ReadonlyArray<Toast>>(getToasts());

    $effect(() => {
        // Re-read synchronously: a toast can be pushed between initialisation and
        // this effect running.
        toasts = getToasts();

        return subscribeToasts(() => {
            toasts = getToasts();
        });
    });
</script>

<!--
    `polite`, not `assertive`: these are failures the user can retry, not
    something that should interrupt a screen reader mid-sentence.

    Mounted unconditionally — including with no toasts yet. A live region only
    announces changes made AFTER it exists in the accessibility tree; gating
    the whole wrapper on `toasts.length > 0` meant the very first toast landed
    before assistive tech was watching the region, so it went unannounced.
-->
<div aria-live="polite" class="lunora-auth-toaster">
    {#each toasts as toast (toast.id)}
        <div class="lunora-auth-toast" role="status">
            <span class="lunora-auth-toast__message">{toast.message}</span>
            <button
                aria-label="Dismiss"
                class="lunora-auth-toast__dismiss"
                onclick={() => {
                    dismissToast(toast.id);
                }}
                type="button"
            >
                ×
            </button>
        </div>
    {/each}
</div>
