// packages/auth-ui/src/vue/PasskeysCard.vue
<script setup lang="ts">
import { ref } from "vue";

import type { AuthPasskey } from "../core";
import { createPasskeysController, isFlowEnabled } from "../core";
import AuthCard from "./AuthCard.vue";
import Field from "./Field.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

const context = useAuthUI();
const t = context.localization;
const enabled = isFlowEnabled(context, "passkey", "PasskeysCard");
const { actions, state } = useController((context_) => createPasskeysController(context_, { autoLoad: enabled }));

const name = ref("");

const passkeyLabel = (passkey: AuthPasskey): string => {
    const label = passkey.name?.trim();

    return label === undefined || label === "" ? t.passkeyUnnamed : label;
};

const onAdd = async (): Promise<void> => {
    await actions.add(name.value);
    name.value = "";
};

const onRemove = (id: string): void => {
    void actions.remove(id);
};
</script>

<template>
    <AuthCard v-if="enabled" :title="t.passkeys">
        <FormBanner :error="state.error" />
        <p v-if="state.loading" class="lunora-auth-card__description">…</p>
        <p v-else-if="state.items.length === 0" class="lunora-auth-card__description">{{ t.passkeysEmpty }}</p>
        <ul v-else class="lunora-auth-list">
            <li v-for="passkey in state.items" :key="passkey.id ?? passkeyLabel(passkey)" class="lunora-auth-list__item">
                <span class="lunora-auth-list__label">{{ passkeyLabel(passkey) }}</span>
                <button v-if="passkey.id !== undefined" class="lunora-auth-link" type="button" :disabled="state.busy" @click="onRemove(passkey.id as string)">
                    {{ t.remove }}
                </button>
            </li>
        </ul>
        <form class="lunora-auth-form" novalidate @submit.prevent="onAdd">
            <Field :field="{ touched: false, value: name }" :label="t.passkeyName" name="passkeyName" @blur="undefined" @change="name = $event" />
            <SubmitButton :pending="state.busy">{{ t.passkeyAdd }}</SubmitButton>
        </form>
    </AuthCard>
</template>

// registry/auth-ui-svelte/svelte/PasskeysCard.svelte
<script lang="ts">
    import type { AuthPasskey } from "../core";
    import { createPasskeysController, isFlowEnabled } from "../core";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import Field from "./Field.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    const context = useAuthUI();
    const t = context.localization;
    const enabled = isFlowEnabled(context, "passkey", "PasskeysCard");
    const { actions, state: res } = controllerStore((context_) => createPasskeysController(context_, { autoLoad: enabled }));

    let name = $state("");

    const passkeyLabel = (passkey: AuthPasskey): string => {
        const label = passkey.name?.trim();

        return label === undefined || label === "" ? t.passkeyUnnamed : label;
    };
</script>

{#if enabled}
    <AuthCard title={t.passkeys}>
        <FormBanner error={$res.error} />
        {#if $res.loading}
            <p class="lunora-auth-card__description">…</p>
        {:else if $res.items.length === 0}
            <p class="lunora-auth-card__description">{t.passkeysEmpty}</p>
        {:else}
            <ul class="lunora-auth-list">
                {#each $res.items as passkey (passkey.id ?? passkeyLabel(passkey))}
                    <li class="lunora-auth-list__item">
                        <span class="lunora-auth-list__label">{passkeyLabel(passkey)}</span>
                        {#if passkey.id !== undefined}
                            <button
                                class="lunora-auth-link"
                                disabled={$res.busy}
                                onclick={() => {
                                    void actions.remove(passkey.id);
                                }}
                                type="button"
                            >
                                {t.remove}
                            </button>
                        {/if}
                    </li>
                {/each}
            </ul>
        {/if}
        <form
            class="lunora-auth-form"
            novalidate
            onsubmit={(event) => {
                event.preventDefault();
                void actions.add(name).then(() => {
                    name = "";
                });
            }}
        >
            <Field
                field={{ touched: false, value: name }}
                label={t.passkeyName}
                name="passkeyName"
                onBlur={() => undefined}
                onChange={(value) => {
                    name = value;
                }}
            />
            <SubmitButton pending={$res.busy}>{t.passkeyAdd}</SubmitButton>
        </form>
    </AuthCard>
{/if}
