// packages/auth-ui/src/vue/SetUsernameCard.vue
<script setup lang="ts">
// Claim or change the username, when the `username` plugin is on.
import { isFlowEnabled } from "../core/flow-gate";
import { createSetUsernameController } from "../core/username";
import AuthCard from "./AuthCard.vue";
import Field from "./Field.vue";
import FormBanner from "./FormBanner.vue";
import { useAuthUI } from "./provider";
import SubmitButton from "./SubmitButton.vue";
import { useController } from "./use-controller";

const context = useAuthUI();
const t = context.localization;
const enabled = isFlowEnabled(context, "username", "SetUsernameCard");
const { actions, state } = useController(createSetUsernameController);
</script>

<template>
    <AuthCard v-if="enabled" :title="t.usernameLabel">
        <form class="lunora-auth-form" novalidate @submit.prevent="actions.submit">
            <FormBanner :error="state.formError" :success="state.successMessage" />
            <Field
                :field="state.fields.username"
                :label="t.usernameLabel"
                name="username"
                autoComplete="username"
                @blur="actions.blur('username')"
                @change="actions.setField('username', $event)"
            />
            <SubmitButton :pending="state.status === 'submitting'">{{ t.saveChanges }}</SubmitButton>
        </form>
    </AuthCard>
</template>

// registry/auth-ui-svelte/svelte/SetUsernameCard.svelte
<!-- Claim or change the username, when the `username` plugin is on. -->
<script lang="ts">
    import { isFlowEnabled } from "../core/flow-gate";
    import { createSetUsernameController } from "../core/username";
    import AuthCard from "./AuthCard.svelte";
    import { useAuthUI } from "./context";
    import { controllerStore } from "./controller-store";
    import Field from "./Field.svelte";
    import FormBanner from "./FormBanner.svelte";
    import SubmitButton from "./SubmitButton.svelte";

    const context = useAuthUI();
    const t = context.localization;
    const enabled = isFlowEnabled(context, "username", "SetUsernameCard");
    const { actions, state: form } = controllerStore(createSetUsernameController);
</script>

{#if enabled}
    <AuthCard title={t.usernameLabel}>
        <form
            class="lunora-auth-form"
            novalidate
            onsubmit={(event) => {
                event.preventDefault();
                void actions.submit();
            }}
        >
            <FormBanner error={$form.formError} success={$form.successMessage} />
            <Field
                autoComplete="username"
                field={$form.fields.username}
                label={t.usernameLabel}
                name="username"
                onBlur={() => {
                    actions.blur("username");
                }}
                onChange={(value) => {
                    actions.setField("username", value);
                }}
            />
            <SubmitButton pending={$form.status === "submitting"}>{t.saveChanges}</SubmitButton>
        </form>
    </AuthCard>
{/if}
