// packages/auth-ui/src/vue/SignOutButton.vue
<script setup lang="ts">
import { signOut } from "../core";
import { useAuthUI } from "./provider";

const props = defineProps<{
    label?: string;
}>();

const context = useAuthUI();
const themeStyle = Object.keys(context.themeVariables).length === 0 ? undefined : context.themeVariables;

const onSignOut = (): void => {
    void signOut(context);
};
</script>

<template>
    <button class="lunora-auth-button lunora-auth-button--secondary" type="button" :style="themeStyle" @click="onSignOut">
        {{ props.label ?? context.localization.signOut }}
    </button>
</template>

// registry/auth-ui-svelte/svelte/SignOutButton.svelte
<script lang="ts">
    import type { Snippet } from "svelte";

    import { signOut } from "../core";
    import { useAuthUI } from "./context";

    let { children }: { children?: Snippet } = $props();

    const context = useAuthUI();
    const themeStyle = Object.entries(context.themeVariables)
        .map(([property, value]) => `${property}:${value}`)
        .join(";");
</script>

<button
    class="lunora-auth-button lunora-auth-button--secondary"
    onclick={() => {
        void signOut(context);
    }}
    style={themeStyle}
    type="button"
>
    {#if children}{@render children()}{:else}{context.localization.signOut}{/if}
</button>
